import { createHash, createSign, randomUUID } from 'node:crypto';

import { type PrismaClient } from '../../database-client/client.js';

const DIRECTORY_ORIGIN = 'https://agendei.site';
const MAX_ATTEMPTS = 5;

export interface DirectorySeoConfiguration {
  siteUrl?: string;
  serviceAccountJson?: string;
  accessToken?: string;
  indexNowKey?: string;
  indexNowEndpoint?: string;
}

interface SearchAnalyticsRow { keys?: string[]; clicks?: number; impressions?: number; ctr?: number; position?: number }
interface GoogleSearchConsoleClient {
  query(input: { siteUrl: string; startDate: string; endDate: string; dimensions: string[] }): Promise<SearchAnalyticsRow[]>;
  listSitemaps(siteUrl: string): Promise<unknown>;
  submitSitemap(siteUrl: string, sitemapUrl: string): Promise<void>;
  inspect(siteUrl: string, inspectionUrl: string): Promise<unknown>;
}

function isoDate(value: Date) { return value.toISOString().slice(0, 10); }
function truncate(value: unknown, max = 1000) { return String(value ?? 'Erro desconhecido.').slice(0, max); }
function canonical(path: string) { return `${DIRECTORY_ORIGIN}${path}`; }
function pageHash(pageUrl: string) { return createHash('sha256').update(pageUrl).digest('hex'); }

class GoogleClient implements GoogleSearchConsoleClient {
  public constructor(private readonly configuration: DirectorySeoConfiguration, private readonly send: typeof fetch = fetch) {}
  private async token() {
    if (this.configuration.accessToken !== undefined) return this.configuration.accessToken;
    if (this.configuration.serviceAccountJson === undefined) throw new Error('Search Console não configurado.');
    const account = JSON.parse(this.configuration.serviceAccountJson) as { client_email?: string; private_key?: string; token_uri?: string };
    if (account.client_email === undefined || account.private_key === undefined) throw new Error('Credencial de serviço Google inválida.');
    const now = Math.floor(Date.now() / 1000); const encode = (value: unknown) => Buffer.from(JSON.stringify(value)).toString('base64url');
    const unsigned = `${encode({ alg: 'RS256', typ: 'JWT' })}.${encode({ iss: account.client_email, scope: 'https://www.googleapis.com/auth/webmasters', aud: account.token_uri ?? 'https://oauth2.googleapis.com/token', iat: now, exp: now + 3600 })}`;
    const signer = createSign('RSA-SHA256'); signer.update(unsigned); signer.end(); const assertion = `${unsigned}.${signer.sign(account.private_key.replace(/\\n/gu, '\n')).toString('base64url')}`;
    const response = await this.send(account.token_uri ?? 'https://oauth2.googleapis.com/token', { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ grant_type: 'urn:ietf:params:oauth:grant-type:jwt-bearer', assertion }) });
    if (!response.ok) throw new Error(`OAuth Google respondeu ${response.status}.`);
    const body = await response.json() as { access_token?: string }; if (body.access_token === undefined) throw new Error('OAuth Google não retornou token.'); return body.access_token;
  }
  private async request(path: string, init: RequestInit = {}) { const response = await this.send(`https://searchconsole.googleapis.com${path}`, { ...init, headers: { authorization: `Bearer ${await this.token()}`, 'content-type': 'application/json', ...init.headers } }); if (!response.ok) throw new Error(`Search Console respondeu ${response.status}.`); return response.status === 204 ? null : response.json(); }
  public async query(input: { siteUrl: string; startDate: string; endDate: string; dimensions: string[] }) { const body = await this.request(`/webmasters/v3/sites/${encodeURIComponent(input.siteUrl)}/searchAnalytics/query`, { method: 'POST', body: JSON.stringify({ startDate: input.startDate, endDate: input.endDate, dimensions: input.dimensions, rowLimit: 25_000, dimensionFilterGroups: [{ filters: [{ dimension: 'page', operator: 'includingRegex', expression: '^https://agendei\\.site/encontre/' }] }] }) }) as { rows?: SearchAnalyticsRow[] }; return body.rows ?? []; }
  public async listSitemaps(siteUrl: string) { return this.request(`/webmasters/v3/sites/${encodeURIComponent(siteUrl)}/sitemaps`); }
  public async submitSitemap(siteUrl: string, sitemapUrl: string) { await this.request(`/webmasters/v3/sites/${encodeURIComponent(siteUrl)}/sitemaps/${encodeURIComponent(sitemapUrl)}`, { method: 'PUT' }); }
  public async inspect(siteUrl: string, inspectionUrl: string) { return this.request('/v1/urlInspection/index:inspect', { method: 'POST', body: JSON.stringify({ siteUrl, inspectionUrl }) }); }
}

export class DirectorySeoService {
  private readonly google: GoogleSearchConsoleClient;
  public constructor(private readonly client: PrismaClient, private readonly configuration: DirectorySeoConfiguration = {}, google?: GoogleSearchConsoleClient, private readonly send: typeof fetch = fetch) { this.google = google ?? new GoogleClient(configuration, send); }
  public configurationStatus() { return { searchConsoleConfigured: this.configuration.siteUrl !== undefined && (this.configuration.accessToken !== undefined || this.configuration.serviceAccountJson !== undefined), indexNowConfigured: this.configuration.indexNowKey !== undefined }; }
  public async status() { const last = await this.client.directorySeoSyncRun.findFirst({ orderBy: { createdAt: 'desc' }, select: { status: true, completedAt: true, createdAt: true, lastError: true } }); return { ...this.configurationStatus(), lastSearchConsoleSyncAt: last?.completedAt ?? null, lastSearchConsoleSyncStatus: last?.status ?? null, lastSearchConsoleSyncError: last?.lastError ?? null, lastSearchConsoleSyncCreatedAt: last?.createdAt ?? null }; }
  private requireGoogle() { if (!this.configurationStatus().searchConsoleConfigured) throw new Error('Search Console não configurado.'); return this.configuration.siteUrl!; }
  private async resolvePage(pageUrl: string) {
    let url: URL; try { url = new URL(pageUrl); } catch { return null; }
    if (url.origin !== DIRECTORY_ORIGIN || !url.pathname.startsWith('/encontre/')) return null;
    const parts = url.pathname.split('/').filter(Boolean); const categorySlug = parts[1]; if (categorySlug === undefined) return { businessId: null, categoryId: null, citySlug: null };
    const category = await this.client.directoryCategory.findUnique({ where: { slug: categorySlug }, select: { id: true } }); if (category === null) return { businessId: null, categoryId: null, citySlug: null };
    const citySlug = parts[2] ?? null;
    if (parts[3] === undefined || citySlug === null) return { businessId: null, categoryId: category.id, citySlug };
    const business = await this.client.directoryBusiness.findFirst({ where: { categoryId: category.id, citySlug, slug: parts[3] }, select: { id: true } });
    return { businessId: business?.id ?? null, categoryId: category.id, citySlug };
  }
  public async enqueueSync() { const now = new Date(); const last = await this.client.directorySeoSyncRun.findFirst({ where: { status: 'DONE' }, orderBy: { completedAt: 'desc' } }); const days = last === null ? 28 : 3; const from = new Date(now); from.setUTCDate(now.getUTCDate() - days); return this.client.directorySeoSyncRun.create({ data: { publicId: randomUUID(), fromDate: from, toDate: now } }); }
  public async processSyncs() {
    if (!this.configurationStatus().searchConsoleConfigured) return { processed: 0, configured: false };
    const run = await this.client.directorySeoSyncRun.findFirst({ where: { status: { in: ['PENDING', 'FAILED'] } }, orderBy: { createdAt: 'asc' } }); if (run === null) return { processed: 0, configured: true };
    await this.client.directorySeoSyncRun.update({ where: { id: run.id }, data: { status: 'PROCESSING', attempts: { increment: 1 }, startedAt: new Date(), lastError: null } });
    try {
      const siteUrl = this.requireGoogle(); const metrics = await this.google.query({ siteUrl, startDate: isoDate(run.fromDate), endDate: isoDate(run.toDate), dimensions: ['date', 'page'] }); const queries = await this.google.query({ siteUrl, startDate: isoDate(run.fromDate), endDate: isoDate(run.toDate), dimensions: ['date', 'page', 'query'] }); const syncedAt = new Date();
      for (const row of metrics) { const [date, pageUrl] = row.keys ?? []; if (date === undefined || pageUrl === undefined) continue; const resolved = await this.resolvePage(pageUrl); if (resolved === null) continue; const hash = pageHash(pageUrl); await this.client.directorySeoDailyMetric.upsert({ where: { date_pageHash: { date: new Date(`${date}T00:00:00.000Z`), pageHash: hash } }, update: { ...resolved, pageUrl, clicks: row.clicks ?? 0, impressions: row.impressions ?? 0, ctr: row.ctr ?? 0, position: row.position ?? 0, syncedAt }, create: { date: new Date(`${date}T00:00:00.000Z`), pageUrl, pageHash: hash, ...resolved, clicks: row.clicks ?? 0, impressions: row.impressions ?? 0, ctr: row.ctr ?? 0, position: row.position ?? 0, syncedAt } }); }
      for (const row of queries) { const [date, pageUrl, query] = row.keys ?? []; if (date === undefined || pageUrl === undefined || query === undefined) continue; const resolved = await this.resolvePage(pageUrl); if (resolved === null) continue; const hash = pageHash(pageUrl); await this.client.directorySeoQueryMetric.upsert({ where: { date_pageHash_query: { date: new Date(`${date}T00:00:00.000Z`), pageHash: hash, query } }, update: { ...resolved, pageUrl, clicks: row.clicks ?? 0, impressions: row.impressions ?? 0, ctr: row.ctr ?? 0, position: row.position ?? 0, syncedAt }, create: { date: new Date(`${date}T00:00:00.000Z`), pageUrl, pageHash: hash, query, ...resolved, clicks: row.clicks ?? 0, impressions: row.impressions ?? 0, ctr: row.ctr ?? 0, position: row.position ?? 0, syncedAt } }); }
      await this.client.directorySeoSyncRun.update({ where: { id: run.id }, data: { status: 'DONE', completedAt: new Date() } }); return { processed: 1, configured: true };
    } catch (error) { await this.client.directorySeoSyncRun.update({ where: { id: run.id }, data: { status: 'FAILED', lastError: truncate(error), completedAt: new Date() } }); return { processed: 0, configured: true }; }
  }
  public async enqueueIndexNow(url: string, reason: 'CREATED' | 'UPDATED' | 'DELETED' | 'MANUAL', businessId?: bigint) { return this.client.seoUrlSubmission.upsert({ where: { provider_url: { provider: 'INDEXNOW', url } }, update: { reason, ...(businessId === undefined ? {} : { businessId }), status: 'PENDING', nextAttemptAt: null, lastError: null, processedAt: null }, create: { publicId: randomUUID(), url, provider: 'INDEXNOW', reason, ...(businessId === undefined ? {} : { businessId }) } }); }
  public async submissions() { return this.client.seoUrlSubmission.findMany({ orderBy: { createdAt: 'desc' }, take: 200, select: { publicId: true, url: true, provider: true, reason: true, status: true, attempts: true, lastError: true, responseStatus: true, createdAt: true, processedAt: true, lastAttemptAt: true } }); }
  public async retrySubmission(publicId: string) { const submission = await this.client.seoUrlSubmission.update({ where: { publicId }, data: { status: 'PENDING', nextAttemptAt: null, lastError: null, processedAt: null } }); return { publicId: submission.publicId, status: submission.status }; }
  public async enqueueManual(url: string) { const parsed = new URL(url); if (parsed.origin !== DIRECTORY_ORIGIN || !parsed.pathname.startsWith('/encontre')) throw new Error('Informe uma URL canônica do Diretório.'); const resolved = await this.resolvePage(url); return this.enqueueIndexNow(url, 'MANUAL', resolved?.businessId ?? undefined); }
  public async sitemapStatus() { if (!this.configurationStatus().searchConsoleConfigured) return { configured: false, sitemap: canonical('/sitemap-directory.xml'), entries: [] as unknown[] }; return { configured: true, sitemap: canonical('/sitemap-directory.xml'), entries: await this.google.listSitemaps(this.requireGoogle()) }; }
  public async submitDirectorySitemap() { const sitemap = canonical('/sitemap-directory.xml'); this.requireGoogle(); await this.google.submitSitemap(this.configuration.siteUrl!, sitemap); return { sitemap, accepted: true }; }
  public async enqueueInspection(url: string, priority = 0, businessId?: bigint) { const parsed = new URL(url); if (parsed.origin !== DIRECTORY_ORIGIN || !parsed.pathname.startsWith('/encontre')) throw new Error('Informe uma URL canônica do Diretório.'); return this.client.seoUrlInspection.upsert({ where: { url }, update: { priority: Math.max(priority, 0), ...(businessId === undefined ? {} : { businessId }), status: 'PENDING', nextAttemptAt: null, lastError: null }, create: { publicId: randomUUID(), url, priority: Math.max(priority, 0), ...(businessId === undefined ? {} : { businessId }) } }); }
  public async inspections() { return this.client.seoUrlInspection.findMany({ take: 100, orderBy: [{ priority: 'desc' }, { createdAt: 'desc' }], select: { publicId: true, url: true, status: true, priority: true, attempts: true, lastError: true, verdict: true, coverageState: true, googleCanonical: true, lastCrawlAt: true, processedAt: true } }); }
  public async processInspections() { if (!this.configurationStatus().searchConsoleConfigured) return { processed: 0, configured: false }; const item = await this.client.seoUrlInspection.findFirst({ where: { status: { in: ['PENDING', 'FAILED'] }, OR: [{ nextAttemptAt: null }, { nextAttemptAt: { lte: new Date() } }], attempts: { lt: MAX_ATTEMPTS } }, orderBy: [{ priority: 'desc' }, { createdAt: 'asc' }] }); if (item === null) return { processed: 0, configured: true }; await this.client.seoUrlInspection.update({ where: { id: item.id }, data: { status: 'PROCESSING', attempts: { increment: 1 }, lastAttemptAt: new Date(), lastError: null } }); try { const response = await this.google.inspect(this.requireGoogle(), item.url) as { inspectionResult?: { indexStatusResult?: { verdict?: string; coverageState?: string; googleCanonical?: string; lastCrawlTime?: string } } }; const status = response.inspectionResult?.indexStatusResult; await this.client.seoUrlInspection.update({ where: { id: item.id }, data: { status: 'DONE', verdict: status?.verdict ?? null, coverageState: status?.coverageState ?? null, googleCanonical: status?.googleCanonical ?? null, lastCrawlAt: status?.lastCrawlTime === undefined ? null : new Date(status.lastCrawlTime), processedAt: new Date() } }); return { processed: 1, configured: true }; } catch (error) { await this.client.seoUrlInspection.update({ where: { id: item.id }, data: { status: 'FAILED', lastError: truncate(error), nextAttemptAt: new Date(Date.now() + 60_000) } }); return { processed: 0, configured: true }; } }
  public async overview(input: { from?: Date; to?: Date; categorySlug?: string; city?: string; search?: string; hasTenant?: boolean } = {}) {
    const until = input.to === undefined ? undefined : new Date(Date.UTC(input.to.getUTCFullYear(), input.to.getUTCMonth(), input.to.getUTCDate(), 23, 59, 59, 999));
    const dates = input.from === undefined && until === undefined ? undefined : { ...(input.from === undefined ? {} : { gte: input.from }), ...(until === undefined ? {} : { lte: until }) };
    const businesses = await this.client.directoryBusiness.findMany({ where: { ...(input.categorySlug === undefined ? {} : { category: { slug: input.categorySlug } }), ...(input.city === undefined ? {} : { city: input.city }), ...(input.search === undefined ? {} : { name: { contains: input.search } }), ...(input.hasTenant === undefined ? {} : { tenantId: input.hasTenant ? { not: null } : null }) }, include: { category: true, seoMetrics: { where: dates === undefined ? {} : { date: dates } }, events: { where: dates === undefined ? {} : { createdAt: dates } } }, orderBy: { name: 'asc' } });
    const rows = businesses.map((business) => { const seo = business.seoMetrics.reduce((value, item) => ({ impressions: value.impressions + item.impressions, googleClicks: value.googleClicks + item.clicks, positionTotal: value.positionTotal + item.position * item.impressions, positionWeight: value.positionWeight + item.impressions }), { impressions: 0, googleClicks: 0, positionTotal: 0, positionWeight: 0 }); const events = business.events.reduce((value, event) => event.type === 'BUSINESS_VIEW' ? { ...value, pageViews: value.pageViews + 1 } : { ...value, whatsappClicks: value.whatsappClicks + 1, visitors: event.visitorHash === null ? value.visitors : new Set([...value.visitors, event.visitorHash]) }, { pageViews: 0, whatsappClicks: 0, visitors: new Set<string>() }); const googleCtr = seo.impressions === 0 ? 0 : seo.googleClicks / seo.impressions; const whatsappConversion = events.pageViews === 0 ? 0 : events.whatsappClicks / events.pageViews; const googleToWhatsapp = seo.googleClicks === 0 ? 0 : events.whatsappClicks / seo.googleClicks; return { businessPublicId: business.publicId, business: business.name, category: business.category.pluralName, city: business.city, state: business.state, tenantLinked: business.tenantId !== null, impressions: seo.impressions, googleClicks: seo.googleClicks, googleCtr, position: seo.positionWeight === 0 ? 0 : seo.positionTotal / seo.positionWeight, pageViews: events.pageViews, whatsappClicks: events.whatsappClicks, uniqueWhatsappClicks: events.visitors.size, whatsappConversion, googleToWhatsapp, score: events.whatsappClicks * 10 + seo.googleClicks + seo.impressions / 100 }; });
    const summary = rows.reduce((value, row) => ({ impressions: value.impressions + row.impressions, googleClicks: value.googleClicks + row.googleClicks, pageViews: value.pageViews + row.pageViews, whatsappClicks: value.whatsappClicks + row.whatsappClicks, weightedPosition: value.weightedPosition + row.position * row.impressions, positionWeight: value.positionWeight + row.impressions }), { impressions: 0, googleClicks: 0, pageViews: 0, whatsappClicks: 0, weightedPosition: 0, positionWeight: 0 });
    return { status: await this.status(), summary: { ...summary, googleCtr: summary.impressions === 0 ? 0 : summary.googleClicks / summary.impressions, position: summary.positionWeight === 0 ? 0 : summary.weightedPosition / summary.positionWeight, pageToWhatsapp: summary.pageViews === 0 ? 0 : summary.whatsappClicks / summary.pageViews, googleToWhatsapp: summary.googleClicks === 0 ? 0 : summary.whatsappClicks / summary.googleClicks }, rows, opportunities: rows.filter((row) => !row.tenantLinked && (row.impressions > 0 || row.googleClicks > 0 || row.whatsappClicks > 0)).sort((a, b) => b.score - a.score) };
  }
  public async queries(input: { from?: Date; to?: Date; categorySlug?: string; citySlug?: string } = {}) { const until = input.to === undefined ? undefined : new Date(Date.UTC(input.to.getUTCFullYear(), input.to.getUTCMonth(), input.to.getUTCDate(), 23, 59, 59, 999)); const items = await this.client.directorySeoQueryMetric.findMany({ where: { ...(input.from === undefined && until === undefined ? {} : { date: { ...(input.from === undefined ? {} : { gte: input.from }), ...(until === undefined ? {} : { lte: until }) } }), ...(input.categorySlug === undefined ? {} : { category: { slug: input.categorySlug } }), ...(input.citySlug === undefined ? {} : { citySlug: input.citySlug }) } }); const grouped = new Map<string, { query: string; clicks: number; impressions: number; positionTotal: number; positionWeight: number }>(); for (const item of items) { const current = grouped.get(item.query) ?? { query: item.query, clicks: 0, impressions: 0, positionTotal: 0, positionWeight: 0 }; current.clicks += item.clicks; current.impressions += item.impressions; current.positionTotal += item.position * item.impressions; current.positionWeight += item.impressions; grouped.set(item.query, current); } return [...grouped.values()].map((item) => ({ query: item.query, clicks: item.clicks, impressions: item.impressions, ctr: item.impressions === 0 ? 0 : item.clicks / item.impressions, position: item.positionWeight === 0 ? 0 : item.positionTotal / item.positionWeight })).sort((a, b) => b.impressions - a.impressions || b.clicks - a.clicks); }
  public async businessDetail(publicId: string) { const business = await this.client.directoryBusiness.findUnique({ where: { publicId }, select: { id: true, publicId: true, name: true, category: { select: { slug: true } }, citySlug: true, slug: true } }); if (business === null) throw new Error('Empresa não encontrada.'); const from = new Date(); from.setUTCDate(from.getUTCDate() - 28); const metrics = await this.client.directorySeoDailyMetric.findMany({ where: { businessId: business.id, date: { gte: from } } }); const queries = await this.client.directorySeoQueryMetric.findMany({ where: { businessId: business.id, date: { gte: from } }, orderBy: { impressions: 'desc' }, take: 20 }); const inspection = await this.client.seoUrlInspection.findFirst({ where: { businessId: business.id }, orderBy: { updatedAt: 'desc' } }); const impressions = metrics.reduce((sum, item) => sum + item.impressions, 0); const clicks = metrics.reduce((sum, item) => sum + item.clicks, 0); const positionWeight = metrics.reduce((sum, item) => sum + item.impressions, 0); const position = positionWeight === 0 ? 0 : metrics.reduce((sum, item) => sum + item.position * item.impressions, 0) / positionWeight; return { business: { publicId: business.publicId, name: business.name, url: canonical(`/encontre/${business.category.slug}/${business.citySlug}/${business.slug}`) }, google: { impressions, clicks, ctr: impressions === 0 ? 0 : clicks / impressions, position }, queries, inspection };
  }
  public async enqueueBusiness(business: { id: bigint; category: { slug: string }; citySlug: string; slug: string }, reason: 'CREATED' | 'UPDATED' | 'MANUAL') { const urls = [canonical('/encontre'), canonical(`/encontre/${business.category.slug}`), canonical(`/encontre/${business.category.slug}/${business.citySlug}`), canonical(`/encontre/${business.category.slug}/${business.citySlug}/${business.slug}`)]; for (const url of urls) await this.enqueueIndexNow(url, reason, url.endsWith(`/${business.slug}`) ? business.id : undefined); await this.enqueueInspection(urls.at(-1)!, reason === 'CREATED' ? 100 : 80, business.id); }
  public async processIndexNow() { if (this.configuration.indexNowKey === undefined) return { processed: 0, configured: false }; const items = await this.client.seoUrlSubmission.findMany({ where: { status: { in: ['PENDING', 'FAILED'] }, OR: [{ nextAttemptAt: null }, { nextAttemptAt: { lte: new Date() } }], attempts: { lt: MAX_ATTEMPTS } }, take: 100, orderBy: { createdAt: 'asc' } }); if (items.length === 0) return { processed: 0, configured: true }; await this.client.seoUrlSubmission.updateMany({ where: { id: { in: items.map((item) => item.id) } }, data: { status: 'PROCESSING', lastAttemptAt: new Date(), attempts: { increment: 1 } } }); try { const endpoint = this.configuration.indexNowEndpoint ?? 'https://api.indexnow.org/indexnow'; const response = await this.send(endpoint, { method: 'POST', headers: { 'content-type': 'application/json; charset=utf-8' }, body: JSON.stringify({ host: 'agendei.site', key: this.configuration.indexNowKey, keyLocation: `${DIRECTORY_ORIGIN}/${this.configuration.indexNowKey}.txt`, urlList: items.map((item) => item.url) }) }); if (!response.ok) throw new Error(`IndexNow respondeu ${response.status}.`); await this.client.seoUrlSubmission.updateMany({ where: { id: { in: items.map((item) => item.id) } }, data: { status: 'DONE', responseStatus: response.status, processedAt: new Date(), lastError: null } }); return { processed: items.length, configured: true }; } catch (error) { const nextAttemptAt = new Date(Date.now() + 60_000); await this.client.seoUrlSubmission.updateMany({ where: { id: { in: items.map((item) => item.id) } }, data: { status: 'FAILED', lastError: truncate(error), nextAttemptAt } }); return { processed: 0, configured: true }; } }
}
