import { describe, expect, it, vi } from 'vitest';
import { TenantSubscriptionService } from './tenant-subscription.service.js';

const currentPlan={id:1n,publicId:'11111111-1111-4111-8111-111111111111',name:'Essencial',sortOrder:1,currency:'BRL',limits:[{key:'professionals.max',valueType:'INTEGER',integerValue:3n,booleanValue:null},{key:'whatsapp.enabled',valueType:'BOOLEAN',integerValue:null,booleanValue:false}]};
const subscription={id:2n,tenantId:3n,planId:1n,status:'ACTIVE',currentPeriodStartsAt:new Date('2026-09-01'),currentPeriodEndsAt:new Date('2026-10-01'),priceCents:1000n,currency:'BRL',billingCycle:'MONTHLY',plan:currentPlan};
const plan=(overrides={})=>({id:4n,publicId:'44444444-4444-4444-8444-444444444444',name:'Premium',sortOrder:2,status:'ACTIVE',isPublic:true,currency:'BRL',limits:[{key:'professionals.max',valueType:'INTEGER',integerValue:10n,booleanValue:null},{key:'whatsapp.enabled',valueType:'BOOLEAN',integerValue:null,booleanValue:true}],billingOptions:[{billingCycle:'MONTHLY',active:true,priceCents:2000n}],...overrides});
function client(target=plan(), active=subscription){return {tenantSubscription:{findFirst:vi.fn().mockResolvedValue(active)},commercialPlan:{findUnique:vi.fn().mockResolvedValue(target)},businessUnit:{count:vi.fn().mockResolvedValue(0)},tenantMembership:{count:vi.fn().mockResolvedValue(0)},professional:{count:vi.fn().mockResolvedValue(6)},service:{count:vi.fn().mockResolvedValue(0)},appointment:{count:vi.fn().mockResolvedValue(0)}}}
describe('TenantSubscriptionService preview',()=>{
 it('identifica upgrade com ganhos, limites e conflito reais',async()=>{const result=await new TenantSubscriptionService(client() as never).previewChange(3n,plan().publicId,'MONTHLY');expect(result.changeType).toBe('UPGRADE');expect(result.gainedFeatures).toContainEqual(expect.objectContaining({label:'WhatsApp'}));expect(result.increasedLimits).toContainEqual(expect.objectContaining({label:'Profissionais'}));});
 it('identifica downgrade, perdas, redução, conflito e data efetiva',async()=>{const high={...currentPlan,id:6n,sortOrder:2,limits:[{key:'professionals.max',valueType:'INTEGER',integerValue:10n,booleanValue:null},{key:'whatsapp.enabled',valueType:'BOOLEAN',integerValue:null,booleanValue:true}]};const low=plan({id:5n,publicId:'55555555-5555-4555-8555-555555555555',name:'Inicial',sortOrder:0,limits:[{key:'professionals.max',valueType:'INTEGER',integerValue:3n,booleanValue:null},{key:'whatsapp.enabled',valueType:'BOOLEAN',integerValue:null,booleanValue:false}]});const result=await new TenantSubscriptionService(client(low,{...subscription,planId:6n,plan:high}) as never).previewChange(3n,low.publicId,'MONTHLY');expect(result.changeType).toBe('DOWNGRADE');expect(result.effectiveAt).toBe(subscription.currentPeriodEndsAt.toISOString());expect(result.usageConflicts).toContainEqual(expect.objectContaining({label:'Profissionais',currentUsage:6,targetLimit:3}));});
 it('rejeita plano atual e plano inativo',async()=>{const same=plan({id:1n});await expect(new TenantSubscriptionService(client(same) as never).previewChange(3n,same.publicId)).rejects.toMatchObject({code:'PLAN_ALREADY_ACTIVE'});const inactive=plan({status:'INACTIVE'});await expect(new TenantSubscriptionService(client(inactive) as never).previewChange(3n,inactive.publicId)).rejects.toMatchObject({code:'PLAN_UNAVAILABLE'});});
});
