CREATE TABLE `system_metadata` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `application_version` VARCHAR(50) NOT NULL,
  `database_initialized_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
