import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { z } from 'zod';
import { httpClient } from '../../../../lib/http.js';

const intents = [['BOOKING', 'Agendamento'], ['AVAILABILITY', 'Consultar horários'], ['PRICE_QUERY', 'Consultar preço'], ['PAYMENT_METHODS', 'Formas de pagamento'], ['PAYMENT', 'Pagamento'], ['CANCEL', 'Cancelamento'], ['RESCHEDULE', 'Reagendamento'], ['BOOKING_QUERY', 'Consultar agendamento']] as const;
const tags = ['{SERVICE}', '{COMBO}', '{PROFESSIONAL}', '{DATE}', '{TIME}', '{DAY_PERIOD}', '{PAYMENT_METHOD}'];
const responseSchema = z.object({ services: z.array(z.object({ publicId: z.string(), name: z.string() })), combos: z.array(z.object({ publicId: z.string(), name: z.string() })), professionals: z.array(z.object({ publicId: z.string(), name: z.string() })), aliases: z.array(z.object({ publicId: z.string(), entityType: z.string(), entityPublicId: z.string(), alias: z.string() })), patterns: z.array(z.object({ publicId: z.string(), intent: z.string(), pattern: z.string(), enabled: z.boolean() })), rules: z.array(z.object({ intent: z.string(), patterns: z.array(z.object({ publicId: z.string(), pattern: z.string() })) })) });
const testSchema = z.object({ intent: z.string(), pattern: z.string().nullable(), source: z.enum(['TENANT_TRAINING', 'PLATFORM']), confidence: z.number(), entities: z.array(z.object({ tag: z.string(), value: z.string(), entity: z.unknown().nullable() })), missingFields: z.array(z.string()), ambiguousEntities: z.array(z.string()) });

export function IntelligenceTab({ tenantPublicId, canManage }: { tenantPublicId: string; canManage: boolean }) {
  const client = useQueryClient(); const [section, setSection] = useState<'vocabulary' | 'training' | 'test'>('vocabulary'); const [selected, setSelected] = useState(''); const [alias, setAlias] = useState(''); const [intent, setIntent] = useState('BOOKING'); const [pattern, setPattern] = useState(''); const [text, setText] = useState(''); const [editing, setEditing] = useState<string | null>(null);
  const queryKey = ['tenant', tenantPublicId, 'whatsapp-intelligence']; const query = useQuery({ queryKey, queryFn: () => httpClient.request('/tenant/integrations/whatsapp/assistant-config/intelligence', { schema: responseSchema, tenantPublicId }) });
  const refresh = () => client.invalidateQueries({ queryKey });
  const addAlias = useMutation({ mutationFn: () => { const [entityType, entityPublicId] = selected.split(':'); return httpClient.request('/tenant/integrations/whatsapp/assistant-config/intelligence/aliases', { method: 'POST', body: { entityType, entityPublicId, alias }, tenantPublicId }); }, onSuccess: async () => { setAlias(''); await refresh(); } });
  const addPattern = useMutation({ mutationFn: () => httpClient.request('/tenant/integrations/whatsapp/assistant-config/intelligence/patterns', { method: 'POST', body: { intent, pattern }, tenantPublicId }), onSuccess: async () => { setPattern(''); await refresh(); } });
  const updatePattern = useMutation({ mutationFn: ({ publicId, body }: { publicId: string; body: { pattern?: string; enabled?: boolean } }) => httpClient.request(`/tenant/integrations/whatsapp/assistant-config/intelligence/patterns/${publicId}`, { method: 'PATCH', body, tenantPublicId }), onSuccess: async () => { setEditing(null); await refresh(); } });
  const removePattern = useMutation({ mutationFn: (publicId: string) => httpClient.request(`/tenant/integrations/whatsapp/assistant-config/intelligence/patterns/${publicId}`, { method: 'DELETE', tenantPublicId }), onSuccess: refresh });
  const simulation = useMutation({ mutationFn: () => httpClient.request('/tenant/integrations/whatsapp/assistant-config/intelligence/simulator', { method: 'POST', body: { text }, schema: testSchema, tenantPublicId }) });
  if (query.isPending) return <section className="wa-card">Carregando inteligência…</section>; if (query.isError || query.data === undefined) return <section className="wa-card">Não foi possível carregar o vocabulário do tenant.</section>;
  const entities = [...query.data.services.map((item) => ({ ...item, type: 'SERVICE', label: `Serviço · ${item.name}` })), ...query.data.combos.map((item) => ({ ...item, type: 'COMBO', label: `Combo · ${item.name}` })), ...query.data.professionals.map((item) => ({ ...item, type: 'PROFESSIONAL', label: `Profissional · ${item.name}` }))];
  return <section className="wa-card"><nav className="wa-tabs" aria-label="Inteligência do tenant">{[['vocabulary', 'Vocabulário'], ['training', 'Treinamento'], ['test', 'Testar']].map(([id, label]) => <button type="button" key={id} className={section === id ? 'is-active' : ''} onClick={() => setSection(id as typeof section)}>{label}</button>)}</nav>
    {section === 'vocabulary' && <><p>Aliases valem somente para este estabelecimento.</p><div style={{ display: 'grid', gap: 8 }}><select value={selected} disabled={!canManage} onChange={(event) => setSelected(event.target.value)}><option value="">Escolha um serviço, combo ou profissional</option>{entities.map((item) => <option key={`${item.type}:${item.publicId}`} value={`${item.type}:${item.publicId}`}>{item.label}</option>)}</select><input value={alias} disabled={!canManage || selected === ''} placeholder="Nome alternativo" onChange={(event) => setAlias(event.target.value)} /><button type="button" disabled={!canManage || selected === '' || alias.trim() === ''} onClick={() => addAlias.mutate()}>Adicionar alias</button></div><ul>{query.data.aliases.map((item) => <li key={item.publicId}>{item.alias} <small>({item.entityType})</small></li>)}</ul></>}
    {section === 'training' && <div style={{ display: 'grid', gap: 16 }}>{intents.map(([key, label]) => { const rule = query.data.rules.find((item) => item.intent === key); const custom = query.data.patterns.filter((item) => item.intent === key); return <article key={key}><h3>{label}</h3><small>Padrões do Agendei (somente leitura)</small><ul>{rule?.patterns.map((item) => <li key={item.publicId}>{item.pattern} <small>Padrão Agendei</small></li>)}</ul><small>Frases deste estabelecimento</small><ul>{custom.map((item) => <li key={item.publicId}>{editing === item.publicId ? <input defaultValue={item.pattern} onBlur={(event) => updatePattern.mutate({ publicId: item.publicId, body: { pattern: event.target.value } })} /> : item.pattern} <button type="button" disabled={!canManage} onClick={() => updatePattern.mutate({ publicId: item.publicId, body: { enabled: !item.enabled } })}>{item.enabled ? 'Desativar' : 'Ativar'}</button> <button type="button" disabled={!canManage} onClick={() => setEditing(item.publicId)}>Editar</button> <button type="button" disabled={!canManage} onClick={() => removePattern.mutate(item.publicId)}>Excluir</button></li>)}</ul>{canManage && <div><input value={intent === key ? pattern : ''} placeholder="Adicionar frase personalizada" onChange={(event) => { setIntent(key); setPattern(event.target.value); }} /><button type="button" disabled={intent !== key || pattern.trim() === ''} onClick={() => addPattern.mutate()}>Adicionar frase</button></div>}<div>Você pode usar: {tags.map((tag) => <button type="button" key={tag} onClick={() => setPattern((value) => `${value}${value === '' ? '' : ' '}${tag}`)}>{tag}</button>)}</div></article>; })}</div>}
    {section === 'test' && <div><p>Digite como um cliente falaria…</p><textarea value={text} disabled={!canManage} onChange={(event) => setText(event.target.value)} /><button type="button" disabled={text.trim() === '' || simulation.isPending} onClick={() => simulation.mutate()}>Interpretar</button>{simulation.data && <div><h3>{simulation.data.missingFields.length > 0 ? 'Interpretação parcial' : simulation.data.intent === 'UNKNOWN' ? 'Não compreendido' : 'Interpretação completa'}</h3><p>Intenção: {simulation.data.intent}</p><p>Origem: {simulation.data.source === 'PLATFORM' ? 'Padrão Agendei' : 'Treinamento do estabelecimento'}</p><p>Pattern: {simulation.data.pattern ?? 'nenhum'}</p><p>Confidence: {Math.round(simulation.data.confidence * 100)}%</p><ul>{simulation.data.entities.map((entity) => <li key={`${entity.tag}:${entity.value}`}>{({ SERVICE: 'Serviço', COMBO: 'Combo', PROFESSIONAL: 'Profissional', DATE: 'Data', TIME: 'Horário', DAY_PERIOD: 'Período', PAYMENT_METHOD: 'Pagamento' } as Record<string, string>)[entity.tag] ?? entity.tag}: {entity.tag === 'DATE' || entity.tag === 'TIME' ? entity.value : entity.entity && typeof entity.entity === 'object' && 'name' in entity.entity ? String(entity.entity.name) : entity.entity ? 'Identificado' : 'Não identificado'}</li>)}</ul><p>Campos faltantes: {simulation.data.missingFields.join(', ') || 'nenhum'}</p><p>Ambiguidades: {simulation.data.ambiguousEntities.join(', ') || 'nenhuma'}</p></div>}</div>}
  </section>;
}
