import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { z } from 'zod';
import { httpClient } from '../../lib/http.js';
import { ErrorState } from './PlatformUi.js';

const city=z.object({id:z.string().optional(),ibgeCode:z.string(),city:z.string(),state:z.string()});
const schema=z.object({data:z.array(z.object({publicId:z.string(),name:z.string(),active:z.boolean(),manager:z.object({publicId:z.string(),displayName:z.string().nullable(),email:z.string()}),cities:z.array(city)}))});
type Region=z.infer<typeof schema>['data'][number];
const label=(x:{displayName:string|null,email:string})=>x.displayName||x.email;

export function CommercialRegionsTab(){
 const cache=useQueryClient(),[editing,setEditing]=useState<Region|null>(null),[confirming,setConfirming]=useState<Region|null>(null);
 const regions=useQuery({queryKey:['platform','commercial','regions'],queryFn:()=>httpClient.request('/platform/commercial/regions',{schema})});
 const refresh=()=>void cache.invalidateQueries({queryKey:['platform','commercial','regions']});
 const remove=useMutation({mutationFn:(id:string)=>httpClient.request(`/platform/commercial/regions/${id}`,{method:'DELETE',schema:z.object({success:z.boolean()})}),onSuccess:()=>{setConfirming(null);setEditing(null);refresh()}});
 const update=useMutation({mutationFn:(region:Region)=>httpClient.request(`/platform/commercial/regions/${region.publicId}`,{method:'PATCH',body:{name:region.name,active:region.active},schema:z.any()}),onSuccess:()=>{setEditing(null);refresh()}});
 if(regions.isPending)return <div className="tab-content">Carregando regiões…</div>;if(regions.error)return <ErrorState message="Erro ao carregar regiões"/>;
 return <div className="tab-content"><header className="section-header"><div><h3>Regiões Comerciais</h3><small>Territórios e cidades cobertas</small></div></header>{editing&&<section className="form-card"><h4>Editar Região</h4><label>Nome da Região<input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label><input type="checkbox" checked={editing.active} onChange={e=>setEditing({...editing,active:e.target.checked})}/> Região ativa</label><div className="chips">{editing.cities.map(c=><span key={c.ibgeCode}>{c.city} - {c.state} <small>IBGE {c.ibgeCode}</small></span>)}</div><div className="form-actions"><button onClick={()=>setEditing(null)}>Cancelar</button><button className="delete-button" onClick={()=>setConfirming(editing)}>Excluir Região</button><button className="action-button" onClick={()=>update.mutate(editing)}>Salvar</button></div></section>}<section className="regions-list">{regions.data.data.map(region=><article key={region.publicId}><div><h4>{region.name}</h4><p>{label(region.manager)} · {region.active?'Ativa':'Inativa'}</p><div className="chips">{region.cities.map(c=><span key={c.ibgeCode}>{c.city} - {c.state} <small>IBGE {c.ibgeCode}</small></span>)}</div></div><aside><small>{region.cities.length} cidades</small><button onClick={()=>setEditing(region)}>Editar</button><button className="delete-button" onClick={()=>setConfirming(region)}>Excluir</button></aside></article>)}</section>{confirming&&<div className="modal-overlay"><div className="modal-content"><h4>Excluir região {confirming.name}?</h4><p>Novos clientes desta região deixarão de ser atribuídos automaticamente. Clientes já vinculados não serão alterados.</p><div className="form-actions"><button onClick={()=>setConfirming(null)}>Cancelar</button><button className="delete-button" disabled={remove.isPending} onClick={()=>remove.mutate(confirming.publicId)}>Excluir Região</button></div></div></div>}<style>{css}</style></div>;
}
const css=`.regions-list{display:grid;gap:10px}.regions-list article,.form-card{padding:16px;border:1px solid var(--border-color);border-radius:10px;background:var(--bg-secondary)}.regions-list article{display:flex;justify-content:space-between;gap:12px}.regions-list h4{margin:0}.regions-list p,small{color:var(--text-secondary)}aside,.form-actions,.chips{display:flex;gap:8px;flex-wrap:wrap}.chips span{padding:5px 8px;border:1px solid var(--border-color);border-radius:14px}.chips small{display:inline}.form-card{display:grid;gap:12px;margin-bottom:16px}.form-card label{display:grid;gap:5px}.form-card input{padding:9px}.delete-button{color:#b91c1c;border:1px solid #ef4444;background:transparent;border-radius:5px;padding:7px 10px}.modal-overlay{position:fixed;inset:0;background:#0008;display:grid;place-items:center;z-index:20}.modal-content{max-width:440px;margin:16px;padding:20px;border-radius:10px;background:var(--bg-primary)}@media(max-width:700px){.regions-list article{flex-direction:column;align-items:stretch}}`;
