import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { z } from 'zod';
import { httpClient } from '../../lib/http.js';
import { ErrorState } from './PlatformUi.js';

const city = z.object({ id: z.string().optional(), ibgeCode: z.string(), city: z.string(), state: z.string() });
const regionSchema = z.object({ data: z.array(z.object({ publicId:z.string(), name:z.string(), active:z.boolean(), manager:z.object({publicId:z.string(),displayName:z.string().nullable(),email:z.string()}), cities:z.array(city) })) });
const accountSchema = z.object({ data: z.array(z.object({ publicId:z.string(),displayName:z.string().nullable(),email:z.string() })) });
const ufs=['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'];
type City=z.infer<typeof city>; type Region=z.infer<typeof regionSchema>['data'][number];
const label=(item:{displayName:string|null,email:string})=>item.displayName||item.email;

export function CommercialRegionsTab(){
 const cache=useQueryClient(); const [current,setCurrent]=useState<Region|null>(null); const [newRegion,setNewRegion]=useState(false); const [manager,setManager]=useState(''); const [name,setName]=useState(''); const [state,setState]=useState(''); const [search,setSearch]=useState(''); const [cities,setCities]=useState<City[]>([]);
 const list=useQuery({queryKey:['platform','commercial','regions'],queryFn:()=>httpClient.request('/platform/commercial/regions',{schema:regionSchema})});
 const accounts=useQuery({queryKey:['platform','commercial','accounts'],queryFn:()=>httpClient.request('/platform/commercial/accounts?role=MANAGER&limit=100',{schema:accountSchema}).then(r=>r.data)});
 const found=useQuery({queryKey:['platform','locations','cities',state,search],enabled:Boolean(state)&&search.trim().length>1,queryFn:()=>httpClient.request(`/platform/locations/cities?state=${state}&search=${encodeURIComponent(search.trim())}`,{schema:z.array(city.omit({id:true}))})});
 const close=()=>{setCurrent(null);setNewRegion(false);setManager('');setName('');setState('');setSearch('');setCities([])};
 const open=(region?:Region)=>{if(region){setCurrent(region);setName(region.name);setCities(region.cities)}else setNewRegion(true)};
 const save=useMutation({mutationFn:()=>current?httpClient.request(`/platform/commercial/regions/${current.publicId}`,{method:'PATCH',body:{name,active:current.active,addCities:cities.filter(c=>!current.cities.some(x=>x.ibgeCode===c.ibgeCode)),removeCityIds:current.cities.filter(c=>!cities.some(x=>x.ibgeCode===c.ibgeCode)).map(c=>c.id)},schema:z.any()}):httpClient.request(`/platform/commercial/managers/${manager}/regions`,{method:'POST',body:{name,cities},schema:z.any()}),onSuccess:()=>{void cache.invalidateQueries({queryKey:['platform','commercial','regions']});close()}});
 const remove=useMutation({mutationFn:(publicId:string)=>httpClient.request(`/platform/commercial/regions/${publicId}`,{method:'DELETE',schema:z.object({success:z.boolean()})}),onSuccess:()=>{void cache.invalidateQueries({queryKey:['platform','commercial','regions']});close()}});
 if(list.isPending||accounts.isPending)return <div className="tab-content">Carregando regiões…</div>; if(list.error||accounts.error)return <ErrorState message="Erro ao carregar regiões"/>; const regions=list.data.data;
 return <div className="tab-content"><header className="section-header"><div><h3>Regiões Comerciais</h3><small>Territórios e cidades cobertas</small></div><button className="action-button" onClick={()=>open()}>+ Nova Região</button></header><div className="summary"><b>{regions.length}<small>Regiões</small></b><b>{regions.reduce((total,r)=>total+r.cities.length,0)}<small>Cidades cobertas</small></b><b>{regions.filter(r=>r.active).length}<small>Ativas</small></b></div>{(newRegion||current)&&<section className="form-card"><h4>{current?'Editar Região':'Nova Região'}</h4>{!current&&<label>Gerente<select value={manager} onChange={e=>setManager(e.target.value)}><option value="">Selecione</option>{accounts.data.map(a=><option key={a.publicId} value={a.publicId}>{label(a)}</option>)}</select></label>}<label>Nome da Região<input value={name} onChange={e=>setName(e.target.value)}/></label>{current&&<label><input type="checkbox" checked={current.active} onChange={e=>setCurrent({...current,active:e.target.checked})}/> Região ativa</label>}<div className="city-form"><label>Estado<select value={state} onChange={e=>{setState(e.target.value);setSearch('')}}><option value="">Selecione</option>{ufs.map(uf=><option key={uf}>{uf}</option>)}</select></label><label>Cidade<input disabled={!state} value={search} onChange={e=>setSearch(e.target.value)} placeholder={state?'Digite 2 letras':'Selecione o estado'}/></label>{found.data&&<div className="suggestions">{found.data.map(c=><button type="button" key={c.ibgeCode} onClick={()=>{if(!cities.some(x=>x.ibgeCode===c.ibgeCode))setCities([...cities,c]);setSearch('')}}>{c.city} — {c.state}</button>)}</div>}</div><div className="chips">{cities.map(c=><span key={c.ibgeCode}>{c.city} - {c.state} <small>IBGE {c.ibgeCode}</small><button type="button" onClick={()=>setCities(cities.filter(x=>x.ibgeCode!==c.ibgeCode))}>×</button></span>)}</div><div className="form-actions"><button onClick={close}>Cancelar</button><button className="action-button" disabled={!name||(!current&&!manager)||save.isPending} onClick={()=>save.mutate()}>Salvar Região</button></div></section>}<section className="regions-list">{regions.map(r=><article key={r.publicId}><div><h4>{r.name}</h4><p>{label(r.manager)} · {r.active?'Ativa':'Inativa'}</p><div className="chips">{r.cities.map(c=><span key={c.ibgeCode}>{c.city} - {c.state} <small>IBGE {c.ibgeCode}</small></span>)}</div></div><aside><small>{r.cities.length} cidades</small><button onClick={()=>open(r)}>Editar</button><button onClick={()=>open(r)}>Ver cidades</button></aside></article>)}</section><style>{css}</style></div>;
}
const css=`.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:16px 0}.summary b,.regions-list article,.form-card{padding:16px;border:1px solid var(--border-color);border-radius:10px;background:var(--bg-secondary)}.summary small{display:block;color:var(--text-secondary)}.summary b{font-size:24px}.form-card{display:grid;gap:12px;margin-bottom:16px}.form-card label{display:grid;gap:6px}.form-card input,.form-card select{padding:9px;border:1px solid var(--border-color);border-radius:5px}.city-form{display:grid;grid-template-columns:180px 1fr;gap:10px}.suggestions{grid-column:2;display:grid}.suggestions button{text-align:left;padding:8px}.chips{display:flex;gap:6px;flex-wrap:wrap}.chips span{padding:5px 8px;border:1px solid var(--border-color);border-radius:15px}.chips small{display:inline}.chips button{border:0;background:none}.regions-list{display:grid;gap:10px}.regions-list article{display:flex;justify-content:space-between}.regions-list h4{margin:0}.regions-list p{color:var(--text-secondary)}aside{display:flex;gap:8px;align-content:flex-start;flex-wrap:wrap}@media(max-width:700px){.summary,.city-form{grid-template-columns:1fr}.suggestions{grid-column:auto}.regions-list article,.section-header{flex-direction:column;align-items:stretch}.section-header .action-button{width:100%}}`;
