import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { z } from 'zod';
import { httpClient } from '../../lib/http.js';
import { ErrorState } from '../platform/PlatformUi.js';
import { PaymentModal } from './PaymentModal.js';

const team=z.object({representatives:z.array(z.object({publicId:z.string(),email:z.string(),displayName:z.string().nullable(),sellers:z.array(z.object({publicId:z.string(),email:z.string(),displayName:z.string().nullable()}))})),directSellers:z.array(z.object({publicId:z.string(),email:z.string(),displayName:z.string().nullable()}))});
const client=z.object({tenantPublicId:z.string(),tenantName:z.string(),subscription:z.any().nullable().optional(),representative:z.object({publicId:z.string(),displayName:z.string().nullable(),email:z.string()}).nullable(),seller:z.object({publicId:z.string(),displayName:z.string().nullable(),email:z.string()}).nullable(),assignedAt:z.string()}); const clientsSchema=z.object({clients:z.array(client)}); const regionSchema=z.object({city:z.string().nullable(),state:z.string().nullable()}); type Client=z.infer<typeof client>;
const label=(x:{displayName:string|null,email:string})=>x.displayName||x.email; const errorText=(x:unknown)=>x instanceof Error?x.message:'Não foi possível concluir a solicitação.';

export function CommercialClientsTab(){const cache=useQueryClient();const [payment,setPayment]=useState<Client|null>(null);const [reassign,setReassign]=useState<Client|null>(null);const clients=useQuery({queryKey:['commercial','clients'],queryFn:()=>httpClient.request('/commercial/clients',{schema:clientsSchema}),retry:false});if(clients.isPending)return <div className="loading"><div className="skeleton-line"/><div className="skeleton-line"/></div>;if(clients.error)return <ErrorState message={errorText(clients.error)}/>;if(!clients.data.clients.length)return <div className="empty-state"><p>Nenhum cliente atribuído</p></div>;return <div className="clients-content"><h3>Clientes Atribuídos</h3><div className="table-container"><table className="data-table"><thead><tr><th>Cliente</th><th>Plano</th><th>Status</th><th>Valor</th><th>Representante</th><th>Vendedor</th><th>Data vínculo</th><th>Ações</th></tr></thead><tbody>{clients.data.clients.map(c=><tr key={c.tenantPublicId}><td><strong>{c.tenantName}</strong></td><td>{c.subscription?.plan?.code||'-'}</td><td>{c.subscription?.status||'INACTIVE'}</td><td>{c.subscription?.priceCents==null?'-':`R$ ${(Number(c.subscription.priceCents)/100).toFixed(2)}`}</td><td>{c.representative?label(c.representative):'-'}</td><td>{c.seller?label(c.seller):'-'}</td><td>{new Date(c.assignedAt).toLocaleDateString('pt-BR')}</td><td><button onClick={()=>setReassign(c)}>Reatribuir</button><button className="btn-mark-paid" onClick={()=>setPayment(c)}>Marcar como pago</button></td></tr>)}</tbody></table></div><div className="client-cards">{clients.data.clients.map(c=><article key={c.tenantPublicId}><strong>{c.tenantName}</strong><span>Plano: {c.subscription?.plan?.code||'-'}</span><span>Status: {c.subscription?.status||'INACTIVE'}</span><span>Valor: {c.subscription?.priceCents==null?'-':`R$ ${(Number(c.subscription.priceCents)/100).toFixed(2)}`}</span><span>Representante: {c.representative?label(c.representative):'-'}</span><span>Vendedor: {c.seller?label(c.seller):'-'}</span><button onClick={()=>setReassign(c)}>Reatribuir</button></article>)}</div>{reassign&&<ReassignModal client={reassign} close={()=>setReassign(null)} done={()=>{setReassign(null);void cache.invalidateQueries({queryKey:['commercial','clients']})}}/>}{payment&&<PaymentModal tenantPublicId={payment.tenantPublicId} tenantName={payment.tenantName} onClose={()=>setPayment(null)} onSuccess={()=>{void clients.refetch();void cache.invalidateQueries({queryKey:['commercial','wallet']})}}/>}<style>{css}</style></div>}
function ReassignModal({client,close,done}:{client:Client,close:()=>void,done:()=>void}){const [repId,setRepId]=useState(client.representative?.publicId||'');const [sellerId,setSellerId]=useState(client.seller?.publicId||'');const members=useQuery({queryKey:['commercial','team','assignment'],queryFn:()=>httpClient.request('/commercial/team',{schema:team})});const save=useMutation({mutationFn:()=>httpClient.request(`/commercial/clients/${client.tenantPublicId}/assignment`,{method:'PATCH',body:{representativePublicId:repId||null,sellerPublicId:sellerId||null},schema:z.object({success:z.boolean()})}),onSuccess:done});const selected=members.data?.representatives.find(x=>x.publicId===repId);const sellers=selected?.sellers??members.data?.directSellers??[];return <div className="modal-overlay" onClick={close}><div className="modal-content" onClick={e=>e.stopPropagation()}><h3>Reatribuir Cliente</h3><p>{client.tenantName}</p>{members.isPending?<p>Carregando equipe...</p>:<form className="assignment-form" onSubmit={e=>{e.preventDefault();if(!save.isPending)save.mutate()}}><div><label>Representante</label><select value={repId} onChange={e=>{setRepId(e.target.value);setSellerId('')}}><option value="">Nenhum (direto ao gerente)</option>{members.data?.representatives.map(x=><option key={x.publicId} value={x.publicId}>{label(x)}</option>)}</select></div><div><label>Vendedor</label><select value={sellerId} onChange={e=>setSellerId(e.target.value)}><option value="">Nenhum</option>{sellers.map(x=><option key={x.publicId} value={x.publicId}>{label(x)}</option>)}</select></div>{save.error&&<div className="error-message">{errorText(save.error)}</div>}<div className="modal-actions"><button type="button" onClick={close} disabled={save.isPending}>Cancelar</button><button className="action-button" disabled={save.isPending}>{save.isPending?'Salvando...':'Salvar'}</button></div></form>}</div></div>}
const css=`.clients-content{display:grid;gap:16px}.table-container{overflow-x:auto;border:1px solid var(--border-color);border-radius:8px}.data-table{width:100%;border-collapse:collapse}.data-table th,.data-table td{padding:12px;text-align:left;border-bottom:1px solid var(--border-color)}.data-table td button{margin-right:6px}.btn-mark-paid{padding:6px 10px}.client-cards{display:none}.assignment-form{display:grid;gap:16px}.assignment-form label{display:block;margin-bottom:6px;font-weight:500}.assignment-form select{width:100%;box-sizing:border-box;padding:9px 12px;border:1px solid var(--border-color);border-radius:5px;background:var(--bg-primary);color:var(--text-primary)}.modal-actions{display:flex;gap:12px}@media(max-width:760px){.table-container{display:none}.client-cards{display:grid;gap:12px}.client-cards article{display:grid;gap:7px;padding:14px;border:1px solid var(--border-color);border-radius:8px}.modal-content{width:calc(100% - 32px)!important;max-width:520px!important;max-height:calc(100vh - 32px);overflow:auto;box-sizing:border-box}}`;
