import { useState } from 'react';
import { billingCycleLabel } from '../../platform/plan-billing-options.js';

type Cycle = 'MONTHLY' | 'QUARTERLY' | 'SEMIANNUAL' | 'ANNUAL';

export function PlanUpgradeCards({ plans, currentId, currentBillingCycle, onSelect }: { plans: any[]; currentId: string; currentBillingCycle: Cycle; onSelect: (id: string, cycle: Cycle) => void }) {
  const [cycles, setCycles] = useState<Record<string, Cycle>>({});
  return <section className="billing-section"><div className="billing-section-heading"><div><span className="billing-kicker">ESCOLHA O PRÓXIMO PASSO</span><h3>Planos disponíveis</h3></div></div><div className="plans-grid">{plans.map(plan => { const current = plan.publicId === currentId; const options = (plan.billingOptions ?? []).filter((option: any) => option.active !== false); const cycle = cycles[plan.publicId] ?? currentBillingCycle; return <article className={`plan-card ${current ? 'is-current' : ''}`} key={plan.publicId}>{current && <span className="plan-card__badge">PLANO ATUAL</span>}<h4>{plan.name}</h4><p>{plan.shortDescription ?? plan.description}</p><strong>{(Number(options.find((option: any) => option.billingCycle === cycle)?.priceCents ?? plan.priceCents) / 100).toLocaleString('pt-BR', { style: 'currency', currency: plan.currency || 'BRL' })}</strong><small>/ {billingCycleLabel(cycle).toLowerCase()}</small>{!current && <><label>Periodicidade<select value={cycle} onChange={event => setCycles(previous => ({ ...previous, [plan.publicId]: event.target.value as Cycle }))}>{options.map((option: any) => <option key={option.billingCycle} value={option.billingCycle}>{billingCycleLabel(option.billingCycle)}</option>)}</select></label><button type="button" onClick={() => onSelect(plan.publicId, cycle)}>Comparar e mudar</button></>}</article>; })}</div></section>;
}
