import { PlatformSubscriptionBillingSchema, SubscriptionChangePreviewSchema, TenantSubscriptionResponseSchema } from '@plataforma/shared';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { z } from 'zod';
import { httpClient } from '../../lib/http.js';
import { usePublicPlans } from '../../marketing/use-public-plans.js';
import { InlineAlert, ListSkeleton, PageHeader } from '../ui/AppUi.js';
import { GatewayPaymentSelector } from './components/GatewayPaymentSelector.js';
import { IncludedFeaturesList } from './components/IncludedFeaturesList.js';
import { InvoicesHistoryTable } from './components/InvoicesHistoryTable.js';
import { PlanUpgradeCards } from './components/PlanUpgradeCards.js';
import { PlanUsageTracker } from './components/PlanUsageTracker.js';
import { SubscriptionStatusHero } from './components/SubscriptionStatusHero.js';
import '../../styles/settings.css'; import '../../styles/subscriptions-additional.css';
const date = (v: string | null) => v ? new Date(v).toLocaleDateString('pt-BR') : '—';
export function TenantSubscriptionModule({ tenantPublicId }: { tenantPublicId: string }) {
  const client = useQueryClient(); const [selectedGateway, setSelectedGateway] = useState<string | null>(null); const [paymentOpen, setPaymentOpen] = useState(false); const [preview, setPreview] = useState<any>(null); const [feedback, setFeedback] = useState<string | null>(null);
  const query = useQuery({ queryKey: ['tenant', tenantPublicId, 'subscription'], queryFn: () => httpClient.request('/tenant/subscription', { schema: TenantSubscriptionResponseSchema, tenantPublicId }), retry: false });
  const billing = useQuery({ queryKey: ['tenant', tenantPublicId, 'subscription', 'billing'], queryFn: () => httpClient.request('/tenant/subscription/billing', { schema: PlatformSubscriptionBillingSchema, tenantPublicId }), retry: false }); const plans = usePublicPlans();
  const charge = useMutation({ mutationFn: async (provider: string) => { if (!preview?.changePublicId) return null; if (provider === 'stripe') { const result = await httpClient.request('/tenant/billing/stripe/checkout', { method: 'POST', body: { changePublicId: preview.changePublicId }, schema: z.object({ url: z.string().url().nullable() }), tenantPublicId }); if (!result.url) throw new Error('O Stripe não retornou uma URL de checkout.'); window.location.assign(result.url); return { kind: 'stripe' as const }; } const result = await httpClient.request(`/tenant/subscription/changes/${preview.changePublicId}/charges`, { method: 'POST', body: { provider }, schema: z.object({ changePublicId: z.uuid(), provider: z.string(), externalId: z.string(), status: z.string(), amountCents: z.string(), currency: z.string(), pixCopyPaste: z.string().nullable() }), tenantPublicId }); return { kind: 'gateway' as const, result }; }, onSuccess: async (result) => { if (result?.kind === 'stripe') return; setFeedback('Pagamento iniciado. O novo plano será ativado após a confirmação.'); await client.invalidateQueries({ queryKey: ['tenant', tenantPublicId, 'subscription', 'billing'] }); setPaymentOpen(false); } });
  const previewChange = useMutation({ mutationFn: ({ planPublicId, billingCycle }: { planPublicId: string; billingCycle: string }) => httpClient.request('/tenant/subscription/change-request', { method: 'POST', body: { planPublicId, billingCycle }, schema: SubscriptionChangePreviewSchema, tenantPublicId }), onSuccess: result => { setPreview(result); if (result.status === 'APPLIED') void client.invalidateQueries({ queryKey: ['tenant', tenantPublicId, 'subscription'] }); } });
  if (query.isPending) return <div className="ds-stack"><PageHeader eyebrow="Assinatura" title="Minha assinatura" description="Gerencie seu plano, pagamentos e consumo." /><ListSkeleton rows={4} /></div>;
  const data = query.data; if (!data) return <div className="ds-stack"><InlineAlert tone="danger" title="Não foi possível carregar sua assinatura" action={<button type="button" onClick={() => void query.refetch()}>Tentar novamente</button>}>Verifique sua conexão e tente novamente.</InlineAlert></div>;
  const latestCharge = billing.data?.latestCharge;
  return <div className="ds-stack tenant-subscription--redesigned"><PageHeader eyebrow="Assinatura" title="Gestão de billing" description="Tudo o que você precisa para acompanhar seu plano e manter sua operação ativa." /><SubscriptionStatusHero plan={data.plan} subscription={data.subscription} commercial={data.commercial} onPay={() => { setPaymentOpen(true); setSelectedGateway(billing.data?.methods[0] ?? null); }} />{charge.error instanceof Error && <InlineAlert tone="danger" title={charge.error.message} />}{paymentOpen && <GatewayPaymentSelector methods={billing.data?.methods ?? []} selected={selectedGateway} onSelect={setSelectedGateway} onPay={() => selectedGateway && void charge.mutate(selectedGateway)} busy={charge.isPending} />}{feedback && <InlineAlert tone="info" title={feedback} />}<PlanUsageTracker limits={data.limits} onUpgrade={() => document.querySelector('.plans-grid')?.scrollIntoView({ behavior: 'smooth' })} /><IncludedFeaturesList limits={data.limits} /><PlanUpgradeCards plans={plans.data?.plans ?? []} currentId={data.plan.publicId} currentBillingCycle={data.subscription.billingCycle as 'MONTHLY' | 'QUARTERLY' | 'SEMIANNUAL' | 'ANNUAL'} onSelect={(id, billingCycle) => void previewChange.mutate({ planPublicId: id, billingCycle })} /><InvoicesHistoryTable charge={latestCharge} onPay={() => setPaymentOpen(true)} />{preview && <div className="app-modal-backdrop" role="presentation"><section className="app-modal" role="dialog" aria-modal="true"><h2>{preview.changeType === 'UPGRADE' ? `Alterar para ${preview.targetPlan.name}?` : `Alteração agendada para ${preview.targetPlan.name}`}</h2><p>Preço do novo período: {(Number(preview.targetPlan.priceCents) / 100).toLocaleString('pt-BR', { style: 'currency', currency: preview.targetPlan.currency || 'BRL' })}</p><p>Crédito não utilizado: {preview.unusedCreditCents ? `-${(Number(preview.unusedCreditCents) / 100).toLocaleString('pt-BR', { style: 'currency', currency: preview.targetPlan.currency || 'BRL' })}` : 'não disponível'}</p><p>Total a pagar agora: {preview.amountDueCents ? (Number(preview.amountDueCents) / 100).toLocaleString('pt-BR', { style: 'currency', currency: preview.targetPlan.currency || 'BRL' }) : 'sem cobrança'}</p><p>{preview.changeType === 'UPGRADE' ? 'Seu novo plano será ativado após a confirmação do pagamento.' : `Seu plano atual continuará ativo até ${date(preview.effectiveAt)}.`}</p>{preview.amountDueCents !== '0' && preview.status !== 'APPLIED' && <button type="button" onClick={() => { setPaymentOpen(true); setSelectedGateway(billing.data?.methods[0] ?? null); }}>Continuar para pagamento</button>}<button type="button" onClick={() => setPreview(null)}>Fechar</button></section></div>}</div>;
}
