import { PlatformChargeResponseSchema,PlatformSubscriptionBillingSchema } from '@plataforma/shared';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';

import { httpClient } from '../../lib/http.js';

/* eslint-disable @typescript-eslint/prefer-optional-chain */

export function TenantSubscriptionPayment({tenantPublicId}:{tenantPublicId:string}){const client=useQueryClient();const [open,setOpen]=useState(false);const billing=useQuery({queryKey:['tenant',tenantPublicId,'subscription','billing'],queryFn:()=>httpClient.request('/tenant/subscription/billing',{schema:PlatformSubscriptionBillingSchema,tenantPublicId}),retry:false});const charge=useMutation({mutationFn:(provider:'pix-local'|'mercadopago')=>httpClient.request('/tenant/subscription/charges',{method:'POST',body:{provider},schema:PlatformChargeResponseSchema,tenantPublicId}),onSuccess:async()=>{await client.invalidateQueries({queryKey:['tenant',tenantPublicId,'subscription','billing']});}});const current=charge.data?.charge??billing.data?.latestCharge;const needsPayment=!current||current.status!=='PAID';return <section className="app-card"><h3>Cobrança da assinatura</h3>{billing.isPending?<p>Carregando métodos de pagamento…</p>:billing.error instanceof Error?<p className="form-error">Não foi possível carregar as opções de pagamento.</p>:<>{current?<dl className="platform-details"><div><dt>Método</dt><dd>{current.provider==='pix-local'?'PIX':'Mercado Pago'}</dd></div><div><dt>Status</dt><dd>{current.status}</dd></div><div><dt>Valor</dt><dd>{(Number(current.amountCents)/100).toLocaleString('pt-BR',{style:'currency',currency:current.currency})}</dd></div></dl>:<p>Nenhuma cobrança gerada.</p>}{needsPayment&&billing.data?.methods.length?<button onClick={()=>{setOpen(true);}} type="button">Pagar assinatura</button>:null}</>}{open?<div className="platform-payment-methods"><h4>Escolha como pagar</h4>{billing.data?.methods.map(method=><button disabled={charge.isPending} key={method} onClick={()=>{void charge.mutateAsync(method);setOpen(false);}} type="button">{method==='pix-local'?'PIX':'Mercado Pago'}</button>)}</div>:null}{charge.data?.qrCodeDataUrl?<img alt="QR Code PIX" className="platform-pix-qr" src={charge.data.qrCodeDataUrl}/>:null}{charge.data?.charge.pixCopyPaste?<><textarea readOnly value={charge.data.charge.pixCopyPaste}/><button onClick={()=>{void navigator.clipboard.writeText(charge.data.charge.pixCopyPaste??'');}} type="button">Copiar código PIX</button><p>Aguardando confirmação</p></>:null}</section>;}
