import { PlatformChargeResponseSchema, PlatformSubscriptionBillingSchema, SubscriptionChangePreviewSchema, TenantSubscriptionResponseSchema } from '@plataforma/shared';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { z } from 'zod';
import { httpClient } from '../../lib/http.js';
import { usePublicPlans } from '../../marketing/use-public-plans.js';
import { InlineAlert, ListSkeleton, PageHeader } from '../ui/AppUi.js';
import { GatewayPaymentSelector } from './components/GatewayPaymentSelector.js';
import { IncludedFeaturesList } from './components/IncludedFeaturesList.js';
import { InvoicesHistoryTable } from './components/InvoicesHistoryTable.js';
import { PlanUpgradeCards } from './components/PlanUpgradeCards.js';
import { PlanUsageTracker } from './components/PlanUsageTracker.js';
import { SubscriptionStatusHero } from './components/SubscriptionStatusHero.js';
import '../../styles/settings.css'; import '../../styles/subscriptions-additional.css';
const date = (v: string | null) => v ? new Date(v).toLocaleDateString('pt-BR') : '—';
export function TenantSubscriptionModule({ tenantPublicId }: { tenantPublicId: string }) {
  const client = useQueryClient(); const [selectedGateway, setSelectedGateway] = useState<string | null>(null); const [paymentOpen, setPaymentOpen] = useState(false); const [preview, setPreview] = useState<any>(null); const [feedback, setFeedback] = useState<string | null>(null);
  const query = useQuery({ queryKey: ['tenant', tenantPublicId, 'subscription'], queryFn: () => httpClient.request('/tenant/subscription', { schema: TenantSubscriptionResponseSchema, tenantPublicId }), retry: false });
  const billing = useQuery({ queryKey: ['tenant', tenantPublicId, 'subscription', 'billing'], queryFn: () => httpClient.request('/tenant/subscription/billing', { schema: PlatformSubscriptionBillingSchema, tenantPublicId }), retry: false }); const plans = usePublicPlans();
  const charge = useMutation({ mutationFn: async (provider: string) => { if (provider === 'stripe') { const result = await httpClient.request('/tenant/billing/stripe/checkout', { method: 'POST', body: { planPublicId: data?.plan.publicId, billingCycle: data?.subscription.billingCycle }, schema: z.object({ url: z.string().url().nullable() }), tenantPublicId }); if (result.url) window.location.assign(result.url); return null; } return httpClient.request('/tenant/subscription/charges', { method: 'POST', body: { provider }, schema: PlatformChargeResponseSchema, tenantPublicId }); }, onSuccess: async () => { await client.invalidateQueries({ queryKey: ['tenant', tenantPublicId, 'subscription', 'billing'] }); setPaymentOpen(false); } });
  const previewChange = useMutation({ mutationFn: (planPublicId: string) => httpClient.request('/tenant/subscription/change-preview', { method: 'POST', body: { planPublicId }, schema: SubscriptionChangePreviewSchema, tenantPublicId }), onSuccess: setPreview });
  const confirmChange = useMutation({ mutationFn: () => httpClient.request('/tenant/subscription/select-plan', { method: 'POST', body: { planPublicId: preview.targetPlan.publicId, billingCycle: preview.targetPlan.billingCycle }, schema: TenantSubscriptionResponseSchema, tenantPublicId }), onSuccess: async result => { setFeedback(`Plano atualizado para ${result.plan.name}.`); setPreview(null); await client.invalidateQueries({ queryKey: ['tenant', tenantPublicId, 'subscription'] }); } });
  if (query.isPending) return <div className="ds-stack"><PageHeader eyebrow="Assinatura" title="Minha assinatura" description="Gerencie seu plano, pagamentos e consumo." /><ListSkeleton rows={4} /></div>;
  const data = query.data; if (!data) return <div className="ds-stack"><InlineAlert tone="danger" title="Não foi possível carregar sua assinatura" action={<button type="button" onClick={() => void query.refetch()}>Tentar novamente</button>}>Verifique sua conexão e tente novamente.</InlineAlert></div>;
  const latestCharge = charge.data?.charge ?? billing.data?.latestCharge;
  return <div className="ds-stack tenant-subscription--redesigned"><PageHeader eyebrow="Assinatura" title="Gestão de billing" description="Tudo o que você precisa para acompanhar seu plano e manter sua operação ativa." /><SubscriptionStatusHero plan={data.plan} subscription={data.subscription} commercial={data.commercial} onPay={() => { setPaymentOpen(true); setSelectedGateway(billing.data?.methods[0] ?? null); }} />{paymentOpen && <GatewayPaymentSelector methods={billing.data?.methods ?? []} selected={selectedGateway} onSelect={setSelectedGateway} onPay={() => selectedGateway && void charge.mutate(selectedGateway)} busy={charge.isPending} />}{charge.data?.qrCodeDataUrl && <section className="pix-result"><img src={charge.data.qrCodeDataUrl} alt="QR Code PIX" /><div><h3>Pagamento PIX gerado</h3><p>Escaneie o QR Code ou copie o código para concluir.</p><textarea readOnly value={charge.data.charge.pixCopyPaste ?? ''} /><button type="button" onClick={() => void navigator.clipboard.writeText(charge.data?.charge.pixCopyPaste ?? '')}>Copiar código PIX</button></div></section>}{feedback && <InlineAlert tone="success" title={feedback} />}<PlanUsageTracker limits={data.limits} onUpgrade={() => document.querySelector('.plans-grid')?.scrollIntoView({ behavior: 'smooth' })} /><IncludedFeaturesList limits={data.limits} /><PlanUpgradeCards plans={plans.data?.plans ?? []} currentId={data.plan.publicId} onSelect={id => void previewChange.mutate(id)} /><InvoicesHistoryTable charge={latestCharge} onPay={() => setPaymentOpen(true)} />{preview && <div className="app-modal-backdrop" role="presentation"><section className="app-modal" role="dialog" aria-modal="true"><h2>{preview.changeType === 'UPGRADE' ? `Fazer upgrade para ${preview.targetPlan.name}?` : `Migrar para ${preview.targetPlan.name}?`}</h2><p>Valor: {(Number(preview.targetPlan.priceCents) / 100).toLocaleString('pt-BR', { style: 'currency', currency: preview.targetPlan.currency || 'BRL' })}</p><p>{preview.changeType === 'UPGRADE' ? 'Você terá acesso imediato aos recursos adicionais.' : `A mudança será efetivada em ${date(preview.effectiveAt)}.`}</p><button type="button" disabled={confirmChange.isPending} onClick={() => void confirmChange.mutate()}>Confirmar mudança</button><button type="button" onClick={() => setPreview(null)}>Cancelar</button></section></div>}</div>;
}
