import { IconAlertTriangle, IconArrowLeft, IconCheck, IconCloud, IconHeadset, IconQrcode } from '@tabler/icons-react';
import { useQuery } from '@tanstack/react-query';
import { z } from 'zod';

import { httpClient } from '../lib/http.js';

const officialAdvantages = ['Integração oficial da Meta', 'Mais previsibilidade para uma operação profissional', 'Templates e webhooks oficiais'];
const ownAdvantages = ['Configuração rápida por QR Code', 'Conexão simples pelo painel', 'Boa opção para atendimento receptivo'];

export function WhatsappApiHelpPage() {
  const contact = useQuery({
    queryKey: ['public', 'commercial-contact'],
    queryFn: () => httpClient.request('/public/commercial-contact', { schema: z.object({ whatsapp: z.string().nullable() }) }),
    staleTime: 5 * 60 * 1000,
  });
  const phone = contact.data?.whatsapp?.replace(/\D/gu, '') ?? '';
  const message = 'Olá! Quero contratar a configuração da Meta API para o meu Agendei.';
  const assistUrl = phone === '' ? null : `https://wa.me/${phone}?text=${encodeURIComponent(message)}`;
  return <main className="whatsapp-help-page">
    <a className="whatsapp-help-back" href="/app/whatsapp/conexao"><IconArrowLeft size={17} /> Voltar para a conexão</a>
    <header className="whatsapp-help-hero"><p className="eyebrow">AJUDA DO AGENDEI</p><h1>Qual conexão do WhatsApp devo escolher?</h1><p>Existem duas formas de conectar o Agendei ao WhatsApp: uma oficial, fornecida pela Meta, e outra por QR Code, não oficial.</p><p className="whatsapp-help-analogy">A API Oficial é como usar a porta da frente construída pela Meta. A API Própria funciona de forma parecida com o WhatsApp Web.</p></header>
    <section className="whatsapp-help-choice-grid">
      <article className="whatsapp-help-choice whatsapp-help-choice--official"><div className="whatsapp-help-icon"><IconCloud /></div><p className="whatsapp-help-kicker">Opção 1</p><h2>API Oficial</h2><p className="whatsapp-help-subtitle">WhatsApp Business Platform da Meta</p><p>É a forma oficial de uma empresa conectar seu sistema ao WhatsApp.</p><ul>{officialAdvantages.map((item) => <li key={item}><IconCheck size={17} />{item}</li>)}</ul><div className="whatsapp-help-callout"><strong>Sobre a cobrança</strong><p>A Meta pode cobrar por determinadas mensagens. Os preços são definidos pela Meta, podem variar conforme categoria, destino e regras vigentes, e não são controlados pelo Agendei.</p></div></article>
      <article className="whatsapp-help-choice whatsapp-help-choice--own"><div className="whatsapp-help-icon"><IconQrcode /></div><p className="whatsapp-help-kicker">Opção 2</p><h2>API Própria</h2><p className="whatsapp-help-subtitle">Conexão por QR Code · não oficial</p><p>É como conectar outro dispositivo ao WhatsApp, usando um QR Code.</p><ul>{ownAdvantages.map((item) => <li key={item}><IconCheck size={17} />{item}</li>)}</ul><div className="whatsapp-help-callout whatsapp-help-callout--warning"><strong>Importante</strong><p>Não há tarifa da Cloud API da Meta por mensagem nesta conexão. O plano do Agendei continua existindo e outros custos do serviço podem existir.</p></div></article>
    </section>
    <section className="whatsapp-help-assistance" aria-labelledby="whatsapp-help-assistance-title"><div className="whatsapp-help-assistance__icon"><IconHeadset /></div><div className="whatsapp-help-assistance__content"><p className="whatsapp-help-kicker">Configuração opcional</p><h2 id="whatsapp-help-assistance-title">Precisa de ajuda para configurar a API Oficial da Meta?</h2><p>Você pode configurar a API Oficial da Meta por conta própria, sem pagar nenhuma taxa de configuração ao Agendei.</p><p>Porém, o processo envolve etapas técnicas como configuração da conta empresarial da Meta, WhatsApp Business Platform, número, permissões, webhooks e integração com o Agendei.</p><p>Se preferir, nossa equipe pode realizar toda a configuração para você.</p><div className="whatsapp-help-assistance__offer"><strong>Configuração assistida da Meta API</strong><b>R$ 250,00</b><span>Taxa única de configuração</span><p>Inclui a configuração necessária para conectar sua conta da Meta ao Agendei e deixar a integração pronta para uso.</p></div>{assistUrl ? <a className="primary-button whatsapp-help-assistance__cta" href={assistUrl} target="_blank" rel="noreferrer">Contratar configuração</a> : null}<small className="whatsapp-help-assistance__notice">A taxa de R$ 250,00 é pelo serviço de configuração realizado pelo Agendei. Eventuais cobranças de mensagens ou outros serviços da Meta são cobradas separadamente pela própria Meta.</small></div></section>
    <section className="whatsapp-help-section"><h2>O que significa “template”?</h2><p>Template é uma mensagem preparada e aprovada pela Meta para certos tipos de contato iniciado pela empresa. Quando um cliente fala com você, responder é diferente de começar uma conversa do nada. A janela de atendimento e as regras de cada mensagem podem mudar.</p><p>Em muitos cenários, é recomendado ou necessário usar um número dedicado. Durante a configuração, o Agendei informa se o número atual pode ser utilizado ou se será necessário outro.</p></section>
    <section className="whatsapp-help-section whatsapp-help-risk"><div className="whatsapp-help-section-heading"><IconAlertTriangle /><div><p className="whatsapp-help-kicker">Leia com atenção</p><h2>Existe risco de bloquear meu WhatsApp?</h2></div></div><p><strong>Sim.</strong> A API Própria não é uma integração oficial. O WhatsApp pode limitar ações, desconectar a sessão, pedir nova verificação, limitar temporariamente ou bloquear o número.</p></section>
    <section className="whatsapp-help-section"><h2>Use um número exclusivo</h2><p>Não recomendamos usar o número mais importante da empresa: aquele que está no Google, no Instagram, que todos os clientes conhecem ou que é usado há muitos anos.</p><div className="whatsapp-help-number-flow"><span>WhatsApp principal<strong>Atendimento humano</strong></span><span>WhatsApp do Agendei<strong>Atendente virtual</strong></span></div></section>
    <section className="whatsapp-help-section"><h2>Use principalmente para receber e responder</h2><div className="whatsapp-help-example-grid"><div><strong>Uso recomendado</strong><p>Cliente: “Olá, quero marcar um horário.”</p><p>Agendei: “Claro! Qual serviço deseja?”</p></div><div className="is-risk"><strong>Maior risco</strong><p>Enviar centenas de mensagens de promoção para pessoas que nunca falaram com a empresa.</p><p>Isso aumenta o risco de denúncias, spam, bloqueios e restrições.</p></div></div><p>Use o Agendei principalmente como atendente receptivo: o cliente chama e o Agendei responde.</p><p>Lembretes esperados, como “Seu horário é amanhã às 14h”, são diferentes de propaganda para desconhecidos. Mesmo assim, use moderação e fale apenas com clientes que têm relação real com sua empresa.</p></section>
    <section className="whatsapp-help-section"><h2>Vai usar automação de cobrança?</h2><p>Recomendamos usar uma sessão e um número exclusivos para o bot de cobrança. Assim você separa as operações, protege o número de atendimento e organiza melhor o trabalho.</p><div className="whatsapp-help-number-flow"><span>Número 1<strong>Atendimento e agendamento</strong></span><span>Número 2<strong>Cobrança e lembretes financeiros</strong></span></div><p>O tipo de cobrança permitido pode depender das regras aplicáveis. Por isso, não trate qualquer mensagem como automaticamente autorizada.</p></section>
    <section className="whatsapp-help-section"><h2>Comparação rápida</h2><div className="whatsapp-help-table-wrap"><table><thead><tr><th>Característica</th><th>API Oficial</th><th>API Própria</th></tr></thead><tbody>{[['Oficial da Meta','Sim','Não'],['QR Code','Não é o fluxo principal','Sim'],['Configuração','Mais técnica','Mais simples'],['Tarifa oficial por mensagem','Pode existir','Não pela Cloud API'],['Templates','Podem ser necessários','Não no fluxo normal'],['Automação','Sim','Sim'],['Risco por integração não oficial','Não','Sim'],['Escala profissional','Mais indicada','Depende do uso'],['Número exclusivo','Frequentemente recomendado','Fortemente recomendado']].map(([a,b,c]) => <tr key={a}><th>{a}</th><td>{b}</td><td>{c}</td></tr>)}</tbody></table></div></section>
    <section className="whatsapp-help-final"><h2>Qual combina com você?</h2><p><strong>Escolha a API Própria se:</strong> quero começar rapidamente, minha operação é principalmente receptiva e aceito o risco de usar uma integração não oficial.</p><p><strong>Escolha a API Oficial se:</strong> quero usar a estrutura oficial da Meta e pretendo ter uma operação mais estruturada ou de maior escala.</p><p>Nenhuma opção elimina a necessidade de usar o WhatsApp com responsabilidade. Evite spam, respeite seus clientes e envie mensagens apenas quando houver uma relação legítima ou autorização para o contato.</p></section>
  </main>;
}
