CREATE TABLE `directory_categories` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(36) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `singular_name` VARCHAR(120) NOT NULL,
  `plural_name` VARCHAR(120) NOT NULL,
  `slug` VARCHAR(120) NOT NULL,
  `description` TEXT NULL,
  `seo_title` VARCHAR(180) NULL,
  `seo_description` VARCHAR(320) NULL,
  `icon` VARCHAR(40) NULL,
  `active` BOOLEAN NOT NULL DEFAULT true,
  `indexable` BOOLEAN NOT NULL DEFAULT true,
  `sort_order` INTEGER NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `udc_public_id` (`public_id`),
  UNIQUE INDEX `udc_slug` (`slug`),
  INDEX `idc_active_sort` (`active`, `sort_order`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `directory_businesses` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(36) NOT NULL,
  `category_id` BIGINT UNSIGNED NOT NULL,
  `tenant_id` BIGINT UNSIGNED NULL,
  `source_local_id` VARCHAR(120) NULL,
  `source_segment_key` VARCHAR(120) NULL,
  `source_search_term` VARCHAR(160) NULL,
  `name` VARCHAR(180) NOT NULL,
  `slug` VARCHAR(180) NOT NULL,
  `city_slug` VARCHAR(180) NOT NULL,
  `raw_address` TEXT NOT NULL,
  `street` VARCHAR(180) NULL,
  `number` VARCHAR(32) NULL,
  `complement` VARCHAR(160) NULL,
  `neighborhood` VARCHAR(120) NULL,
  `city` VARCHAR(120) NOT NULL,
  `state` CHAR(2) NOT NULL,
  `postal_code` CHAR(8) NULL,
  `ibge_code` VARCHAR(16) NULL,
  `phone` VARCHAR(20) NULL,
  `whatsapp` VARCHAR(20) NULL,
  `email` VARCHAR(254) NULL,
  `website_url` VARCHAR(500) NULL,
  `image_url` VARCHAR(500) NULL,
  `source_url` VARCHAR(500) NULL,
  `relevance_score` INTEGER NULL,
  `review_status` VARCHAR(40) NULL,
  `active` BOOLEAN NOT NULL DEFAULT true,
  `indexable` BOOLEAN NOT NULL DEFAULT true,
  `source_hash` CHAR(64) NOT NULL,
  `first_imported_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `last_imported_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `claimed_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `udb_public_id` (`public_id`),
  UNIQUE INDEX `udb_category_city_slug` (`category_id`, `state`, `city_slug`, `slug`),
  INDEX `idb_category_city_active` (`category_id`, `city_slug`, `active`),
  INDEX `idb_city_state` (`city`, `state`),
  INDEX `idb_ibge` (`ibge_code`),
  INDEX `idb_whatsapp` (`whatsapp`),
  INDEX `idb_phone` (`phone`),
  INDEX `idb_tenant` (`tenant_id`),
  CONSTRAINT `fdb_category` FOREIGN KEY (`category_id`) REFERENCES `directory_categories`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fdb_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `directory_imports` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(36) NOT NULL,
  `filename` VARCHAR(255) NOT NULL,
  `status` ENUM('ANALYZED','QUEUED','PROCESSING','PAUSED','COMPLETED','FAILED') NOT NULL DEFAULT 'ANALYZED',
  `total_found` INTEGER NOT NULL DEFAULT 0,
  `total_selected` INTEGER NOT NULL DEFAULT 0,
  `total_created` INTEGER NOT NULL DEFAULT 0,
  `total_updated` INTEGER NOT NULL DEFAULT 0,
  `total_unchanged` INTEGER NOT NULL DEFAULT 0,
  `total_duplicates` INTEGER NOT NULL DEFAULT 0,
  `processed_count` INTEGER NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `completed_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `udi_public_id` (`public_id`),
  INDEX `idi_status_created` (`status`, `created_at`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `directory_import_items` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `import_id` BIGINT UNSIGNED NOT NULL,
  `category_id` BIGINT UNSIGNED NULL,
  `business_id` BIGINT UNSIGNED NULL,
  `source_local_id` VARCHAR(120) NULL,
  `category_detected` VARCHAR(160) NULL,
  `status` ENUM('CREATED','UPDATED','UNCHANGED','POSSIBLE_DUPLICATE','SKIPPED','ERROR') NOT NULL DEFAULT 'SKIPPED',
  `position` INTEGER NOT NULL,
  `source_data` JSON NOT NULL,
  `message` VARCHAR(500) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `udi_import_position` (`import_id`, `position`),
  INDEX `idii_import_status` (`import_id`, `status`),
  CONSTRAINT `fdii_import` FOREIGN KEY (`import_id`) REFERENCES `directory_imports`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fdii_category` FOREIGN KEY (`category_id`) REFERENCES `directory_categories`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fdii_business` FOREIGN KEY (`business_id`) REFERENCES `directory_businesses`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
