import { WhatsAppAssistantConfigResponseSchema, SuccessResponseSchema, type WhatsAppAssistantConfig } from '@plataforma/shared';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { IconCircleCheck, IconPlugConnected } from '@tabler/icons-react';
import { httpClient } from '../../../lib/http.js';
import { TabsHeader, type WhatsappTab } from './components/TabsHeader.js';
import { MenuSettingsTab } from './components/MenuSettingsTab.js';
import { AutomatedMessagesTab } from './components/AutomatedMessagesTab.js';
import { WhatsappPreview } from './components/WhatsappPreview.js';
import { UnsavedChangesBar } from './components/UnsavedChangesBar.js';
import { z } from 'zod';

export function WhatsappSettings({ tenantPublicId, canManage, whatsappConnected }: { tenantPublicId: string; canManage: boolean; whatsappConnected: boolean }) {
  const navigate = useNavigate(); const client = useQueryClient(); const [tab, setTab] = useState<WhatsappTab>('menu'); const [draft, setDraft] = useState<WhatsAppAssistantConfig | null>(null); const [saved, setSaved] = useState<WhatsAppAssistantConfig | null>(null);
  const queryKey = ['tenant', tenantPublicId, 'whatsapp-assistant-config'];
  const query = useQuery({ queryKey, queryFn: () => httpClient.request('/tenant/integrations/whatsapp/assistant-config', { schema: WhatsAppAssistantConfigResponseSchema, tenantPublicId }), retry: false });
  useEffect(() => { if (query.data?.config && !saved) { setSaved(query.data.config); setDraft(query.data.config); } }, [query.data, saved]);
  const mutation = useMutation({ mutationFn: (config: WhatsAppAssistantConfig) => httpClient.request('/tenant/integrations/whatsapp/assistant-config', { method: 'PATCH', body: config, schema: SuccessResponseSchema, tenantPublicId }), onSuccess: async () => { await client.invalidateQueries({ queryKey }); setSaved(draft); } });
  const audioSchema = z.object({ enabled: z.boolean(), provider: z.string(), configured: z.boolean(), languageCode: z.string(), maxAudioSeconds: z.number(), lastValidatedAt: z.string().nullable(), lastValidationStatus: z.string().nullable() });
  const audio = useQuery({ queryKey: ['tenant', tenantPublicId, 'whatsapp-audio'], queryFn: () => httpClient.request('/tenant/integrations/whatsapp/audio-transcription', { schema: audioSchema, tenantPublicId }), enabled: tab === 'audio' });
  const audioMutation = useMutation({ mutationFn: (body: { enabled: boolean; apiKey?: string }) => httpClient.request('/tenant/integrations/whatsapp/audio-transcription', { method: 'PUT', body, schema: audioSchema, tenantPublicId }), onSuccess: () => client.invalidateQueries({ queryKey: ['tenant', tenantPublicId, 'whatsapp-audio'] }) });
  const [audioEnabled, setAudioEnabled] = useState(false); const [audioKey, setAudioKey] = useState('');
  const isDirty = !!draft && !!saved && JSON.stringify(draft) !== JSON.stringify(saved);
  const previewMessage = draft?.greeting.enabled ? draft.greeting.newCustomerBody : 'Escolha uma das opções abaixo para continuar.';
  const previewMenu = useMemo(() => draft?.menu.buttons ?? [], [draft]);
  if (query.isPending || !draft) return <div className="wa-settings-loading">Carregando configurações…</div>;
  if (query.isError) return <div className="wa-settings-error">Não foi possível carregar as configurações. <button type="button" onClick={() => query.refetch()}>Tentar novamente</button></div>;
  return <div className="wa-settings-shell"><header className="wa-settings-header"><div><span className="wa-kicker">WHATSAPP · ASSISTENTE VIRTUAL</span><h1>Atendimento automático</h1><p>Personalize as mensagens automáticas e o comportamento do assistente virtual.</p></div><div className={`wa-connection-pill ${whatsappConnected ? 'connected' : ''}`}><span />{whatsappConnected ? 'WhatsApp conectado' : 'WhatsApp não conectado'}</div></header><TabsHeader activeTab={tab} onChange={setTab} /><div className="wa-settings-grid"><main>{tab === 'menu' && <MenuSettingsTab greeting={draft.greeting} menu={draft.menu} canManage={canManage} onChange={(next) => setDraft({ ...draft, ...next })} />}{tab === 'automated' && <AutomatedMessagesTab canManage={canManage} responseIntervalSeconds={draft.responseIntervalSeconds} onIntervalChange={(value) => setDraft({ ...draft, responseIntervalSeconds: value })} />}{tab === 'connection' && <section className="wa-card"><h2>Inteligência</h2><p>Gerencie vocabulário, treinamento e testes do assistente na área dedicada.</p><button className="btn btn-primary" type="button" onClick={() => void navigate('/app/whatsapp/inteligencia')}>Gerenciar Inteligência</button></section>}{tab === 'audio' && <section className="wa-card"><h2>Entender mensagens de áudio</h2><p>Quando um cliente enviar um áudio pelo WhatsApp, o Agendei transforma a fala em texto e usa a mesma inteligência das mensagens escritas.</p><label><input type="checkbox" checked={audioEnabled || audio.data?.enabled === true} onChange={(e) => setAudioEnabled(e.target.checked)} /> Ativar atendimento por áudio</label><p>{audio.data?.configured ? '✓ Chave configurada' : 'Nenhuma chave configurada'}</p><input type="password" value={audioKey} onChange={(e) => setAudioKey(e.target.value)} placeholder="Chave API AssemblyAI" autoComplete="new-password" /><button className="btn btn-primary" type="button" disabled={!canManage || audioMutation.isPending} onClick={() => audioMutation.mutate({ enabled: audioEnabled || audio.data?.enabled === true, ...(audioKey ? { apiKey: audioKey } : {}) })}>Salvar</button>{audio.data?.configured && <button className="btn" type="button" onClick={() => void httpClient.request('/tenant/integrations/whatsapp/audio-transcription/test', { method: 'POST', body: {}, schema: z.object({ success: z.boolean(), message: z.string().optional() }), tenantPublicId })}>Testar conexão</button>}</section>}</main>{tab === 'menu' && <WhatsappPreview message={previewMessage} showMenu={draft.menu.buttons.some((button) => button.enabled)} menu={previewMenu} />}</div>{isDirty && canManage && <UnsavedChangesBar saving={mutation.isPending} disabled={mutation.isPending} onDiscard={() => setDraft(saved)} onSave={() => mutation.mutate(draft)} />}</div>;
}
