CREATE TABLE `stock_movements` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(36) NOT NULL,
  `transfer_public_id` CHAR(36) NULL,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `product_id` BIGINT UNSIGNED NOT NULL,
  `business_unit_id` BIGINT UNSIGNED NOT NULL,
  `related_business_unit_id` BIGINT UNSIGNED NULL,
  `type` ENUM('ENTRY', 'MANUAL_EXIT', 'POSITIVE_ADJUSTMENT', 'NEGATIVE_ADJUSTMENT', 'TRANSFER_OUT', 'TRANSFER_IN') NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `previous_quantity` INT UNSIGNED NOT NULL,
  `resulting_quantity` INT UNSIGNED NOT NULL,
  `reason` VARCHAR(500) NULL,
  `performed_by_user_id` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `stock_movements_public_id_key` (`public_id`),
  INDEX `stock_movements_tenant_id_created_at_idx` (`tenant_id`, `created_at`),
  INDEX `stock_movements_tenant_id_product_id_business_unit_id_created_at_idx` (`tenant_id`, `product_id`, `business_unit_id`, `created_at`),
  INDEX `stock_movements_transfer_public_id_idx` (`transfer_public_id`),
  INDEX `stock_movements_performed_by_user_id_created_at_idx` (`performed_by_user_id`, `created_at`),
  CONSTRAINT `stock_movements_tenant_id_fkey` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `stock_movements_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `stock_movements_business_unit_id_fkey` FOREIGN KEY (`business_unit_id`) REFERENCES `business_units`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `stock_movements_related_business_unit_id_fkey` FOREIGN KEY (`related_business_unit_id`) REFERENCES `business_units`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `stock_movements_performed_by_user_id_fkey` FOREIGN KEY (`performed_by_user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
