CREATE TABLE `professionals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(36) NOT NULL,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `primary_unit_id` BIGINT UNSIGNED NULL,
  `name` VARCHAR(120) NOT NULL,
  `public_name` VARCHAR(120) NOT NULL,
  `bio` VARCHAR(2000) NULL,
  `photo_path` VARCHAR(512) NULL,
  `phone` VARCHAR(32) NULL,
  `email` VARCHAR(254) NULL,
  `professional_document` VARCHAR(80) NULL,
  `specialties` JSON NULL,
  `calendar_color` CHAR(7) NOT NULL,
  `sort_order` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `active` BOOLEAN NOT NULL DEFAULT TRUE,
  `custom_fields` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`), UNIQUE INDEX `professionals_public_id_key` (`public_id`),
  INDEX `professionals_tenant_id_active_sort_order_idx` (`tenant_id`, `active`, `sort_order`),
  INDEX `professionals_tenant_id_primary_unit_id_idx` (`tenant_id`, `primary_unit_id`),
  CONSTRAINT `professionals_tenant_id_fkey` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `professionals_primary_unit_id_fkey` FOREIGN KEY (`primary_unit_id`) REFERENCES `business_units`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
