-- PROSPECTING — Etapa 3.2: Add NEEDS_REVIEW status for delivery-uncertain messages
ALTER TABLE `prospecting_leads` MODIFY COLUMN `status` ENUM('PENDING', 'SCHEDULED', 'CONTACTED', 'WAITING_REPLY', 'RESPONDED', 'QUALIFYING', 'INTERESTED', 'DEMO_SENT', 'FOLLOW_UP', 'WON', 'LOST', 'NO_RESPONSE', 'SUPPRESSED', 'FAILED', 'NEEDS_REVIEW') NOT NULL DEFAULT 'PENDING';
