import { Link } from 'react-router-dom';

import { MarketingShell } from './MarketingShell.js';
import { marketingSiteUrl, usePageMetadata } from './use-page-metadata.js';

type Faq = { question: string; answer: string };
type Section = { title: string; text: string };

export function SeoLandingPage({ title, description, path, headline, lead, pain, sections, faq, links, heroImage }: { title: string; description: string; path: string; headline: string; lead: string; pain: string; sections: Section[]; faq: Faq[]; links: { to: string; label: string }[]; heroImage?: { src: string; alt: string } }) {
  usePageMetadata({ title, description, path, structuredData: [{ '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Agendei', applicationCategory: 'BusinessApplication', operatingSystem: 'Web', description, url: `${marketingSiteUrl}${path}` }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) }] });
  return <MarketingShell><section className="marketing-page-hero"><div className={heroImage ? 'marketing-container seo-landing-hero' : 'marketing-container marketing-page-hero-inner'}><div><p className="marketing-kicker">Agendei para serviços com hora marcada</p><h1>{headline}</h1><p>{lead}</p><Link className="marketing-button" to="/planos">Teste grátis por 7 dias</Link></div>{heroImage ? <img className="seo-landing-hero-image" src={heroImage.src} alt={heroImage.alt} decoding="async" fetchPriority="high" /> : null}</div></section><section className="marketing-section marketing-value-section"><div className="marketing-container"><p className="marketing-eyebrow">A dor da rotina</p><h2>{pain}</h2></div></section><section className="marketing-section"><div className="marketing-container"><div className="feature-groups">{sections.map((section, index) => <article className="feature-group" key={section.title}><span className="feature-group-number">{String(index + 1).padStart(2, '0')}</span><div><h2>{section.title}</h2><p>{section.text}</p></div></article>)}</div></div></section><section className="marketing-section marketing-audience"><div className="marketing-container"><p className="marketing-eyebrow">Também pode ajudar</p><div className="audience-list">{links.map((link) => <Link key={link.to} to={link.to}>{link.label}</Link>)}<Link to="/funcionalidades">Explorar todas as funcionalidades</Link></div></div></section><section className="marketing-section faq-section"><div className="marketing-container"><p className="marketing-eyebrow">Perguntas frequentes</p><h2>Respostas para decidir com clareza.</h2><div className="faq-list">{faq.map((item) => <details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</div></div></section><section className="marketing-final-cta"><div className="marketing-container marketing-final-cta-inner"><div><h2>Organize a operação sem perder o ritmo do atendimento.</h2><p>Conheça o Agendei e comece com um teste gratuito.</p></div><Link className="marketing-button marketing-button--light" to="/planos">Começar agora</Link></div></section></MarketingShell>;
}
