CREATE TABLE `directory_seo_daily_metrics` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `page_url` VARCHAR(700) NOT NULL,
  `page_hash` CHAR(64) NOT NULL,
  `business_id` BIGINT UNSIGNED NULL,
  `category_id` BIGINT UNSIGNED NULL,
  `city_slug` VARCHAR(180) NULL,
  `clicks` DOUBLE NOT NULL DEFAULT 0,
  `impressions` DOUBLE NOT NULL DEFAULT 0,
  `ctr` DOUBLE NOT NULL DEFAULT 0,
  `position` DOUBLE NOT NULL DEFAULT 0,
  `synced_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `udsdm_date_page` (`date`, `page_hash`),
  INDEX `idsdm_date` (`date`),
  INDEX `idsdm_business_date` (`business_id`, `date`),
  INDEX `idsdm_category_date` (`category_id`, `date`),
  CONSTRAINT `fdsdm_business` FOREIGN KEY (`business_id`) REFERENCES `directory_businesses` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fdsdm_category` FOREIGN KEY (`category_id`) REFERENCES `directory_categories` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `directory_seo_query_metrics` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `page_url` VARCHAR(700) NOT NULL,
  `page_hash` CHAR(64) NOT NULL,
  `query` VARCHAR(500) NOT NULL,
  `business_id` BIGINT UNSIGNED NULL,
  `category_id` BIGINT UNSIGNED NULL,
  `city_slug` VARCHAR(180) NULL,
  `clicks` DOUBLE NOT NULL DEFAULT 0,
  `impressions` DOUBLE NOT NULL DEFAULT 0,
  `ctr` DOUBLE NOT NULL DEFAULT 0,
  `position` DOUBLE NOT NULL DEFAULT 0,
  `synced_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `udsqm_date_page_query` (`date`, `page_hash`, `query`),
  INDEX `idsqm_date` (`date`),
  INDEX `idsqm_business_date` (`business_id`, `date`),
  INDEX `idsqm_category_date` (`category_id`, `date`),
  CONSTRAINT `fdsqm_business` FOREIGN KEY (`business_id`) REFERENCES `directory_businesses` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fdsqm_category` FOREIGN KEY (`category_id`) REFERENCES `directory_categories` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `directory_seo_sync_runs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(36) NOT NULL,
  `status` ENUM('PENDING','PROCESSING','DONE','FAILED') NOT NULL DEFAULT 'PENDING',
  `from_date` DATE NOT NULL,
  `to_date` DATE NOT NULL,
  `attempts` INT NOT NULL DEFAULT 0,
  `last_error` VARCHAR(1000) NULL,
  `started_at` DATETIME(3) NULL,
  `completed_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `udssr_public_id` (`public_id`),
  INDEX `idssr_status_created` (`status`, `created_at`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `seo_url_submissions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(36) NOT NULL,
  `url` VARCHAR(700) NOT NULL,
  `provider` ENUM('INDEXNOW') NOT NULL,
  `reason` ENUM('CREATED','UPDATED','DELETED','MANUAL') NOT NULL,
  `status` ENUM('PENDING','PROCESSING','DONE','FAILED') NOT NULL DEFAULT 'PENDING',
  `business_id` BIGINT UNSIGNED NULL,
  `attempts` INT NOT NULL DEFAULT 0,
  `last_error` VARCHAR(1000) NULL,
  `response_status` INT NULL,
  `last_attempt_at` DATETIME(3) NULL,
  `processed_at` DATETIME(3) NULL,
  `next_attempt_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usu_public_id` (`public_id`),
  UNIQUE INDEX `usu_provider_url` (`provider`, `url`),
  INDEX `isu_status_next` (`status`, `next_attempt_at`),
  INDEX `isu_business` (`business_id`),
  CONSTRAINT `fsu_business` FOREIGN KEY (`business_id`) REFERENCES `directory_businesses` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `seo_url_inspections` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(36) NOT NULL,
  `url` VARCHAR(700) NOT NULL,
  `business_id` BIGINT UNSIGNED NULL,
  `status` ENUM('PENDING','PROCESSING','DONE','FAILED') NOT NULL DEFAULT 'PENDING',
  `priority` INT NOT NULL DEFAULT 0,
  `attempts` INT NOT NULL DEFAULT 0,
  `last_error` VARCHAR(1000) NULL,
  `verdict` VARCHAR(80) NULL,
  `coverage_state` VARCHAR(160) NULL,
  `google_canonical` VARCHAR(700) NULL,
  `last_crawl_at` DATETIME(3) NULL,
  `last_attempt_at` DATETIME(3) NULL,
  `processed_at` DATETIME(3) NULL,
  `next_attempt_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sui_public_id` (`public_id`),
  UNIQUE INDEX `sui_url` (`url`),
  INDEX `isui_status_priority_next` (`status`, `priority`, `next_attempt_at`),
  INDEX `isui_business` (`business_id`),
  CONSTRAINT `fsui_business` FOREIGN KEY (`business_id`) REFERENCES `directory_businesses` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
