CREATE TABLE `appointment_waitlist_opportunities` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(36) NOT NULL,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `released_appointment_id` BIGINT UNSIGNED NOT NULL,
  `professional_id` BIGINT UNSIGNED NOT NULL,
  `service_id` BIGINT UNSIGNED NOT NULL,
  `unit_id` BIGINT UNSIGNED NOT NULL,
  `starts_at` DATETIME(3) NOT NULL,
  `claimed_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `appointment_waitlist_opportunities_public_id_key` (`public_id`),
  UNIQUE INDEX `appointment_waitlist_opportunities_released_appointment_id_key` (`released_appointment_id`),
  INDEX `waitlist_opportunity_match_idx` (`tenant_id`, `service_id`, `unit_id`, `starts_at`, `claimed_at`),
  PRIMARY KEY (`id`),
  CONSTRAINT `waitlist_opportunity_tenant_fk` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `waitlist_opportunity_appointment_fk` FOREIGN KEY (`released_appointment_id`) REFERENCES `appointments`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `waitlist_opportunity_professional_fk` FOREIGN KEY (`professional_id`) REFERENCES `professionals`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `waitlist_opportunity_service_fk` FOREIGN KEY (`service_id`) REFERENCES `services`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `waitlist_opportunity_unit_fk` FOREIGN KEY (`unit_id`) REFERENCES `business_units`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `appointment_waitlists` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(36) NOT NULL,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `customer_id` BIGINT UNSIGNED NOT NULL,
  `professional_id` BIGINT UNSIGNED NULL,
  `service_id` BIGINT UNSIGNED NOT NULL,
  `unit_id` BIGINT UNSIGNED NOT NULL,
  `preferred_date_from` DATE NOT NULL,
  `preferred_date_to` DATE NOT NULL,
  `preferred_time_start` CHAR(5) NOT NULL,
  `preferred_time_end` CHAR(5) NOT NULL,
  `expires_at` DATETIME(3) NOT NULL,
  `notes` VARCHAR(2000) NULL,
  `status` ENUM('WAITING','MATCHED','CONVERTED','EXPIRED','CANCELED') NOT NULL DEFAULT 'WAITING',
  `matched_at` DATETIME(3) NULL,
  `converted_at` DATETIME(3) NULL,
  `canceled_at` DATETIME(3) NULL,
  `canceled_reason` VARCHAR(500) NULL,
  `appointment_id` BIGINT UNSIGNED NULL,
  `opportunity_id` BIGINT UNSIGNED NULL,
  `active_identity` VARCHAR(191) GENERATED ALWAYS AS (CASE WHEN `status` IN ('WAITING','MATCHED') THEN CONCAT(`tenant_id`, ':', `customer_id`, ':', `service_id`, ':', `unit_id`) ELSE NULL END) STORED,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `appointment_waitlists_public_id_key` (`public_id`),
  UNIQUE INDEX `appointment_waitlists_appointment_id_key` (`appointment_id`),
  UNIQUE INDEX `appointment_waitlists_opportunity_id_key` (`opportunity_id`),
  UNIQUE INDEX `appointment_waitlists_active_identity_key` (`active_identity`),
  INDEX `waitlist_status_expiry_fifo_idx` (`tenant_id`, `status`, `expires_at`, `created_at`),
  INDEX `waitlist_match_idx` (`tenant_id`, `professional_id`, `service_id`, `unit_id`),
  PRIMARY KEY (`id`),
  CONSTRAINT `waitlist_tenant_fk` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `waitlist_customer_fk` FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `waitlist_professional_fk` FOREIGN KEY (`professional_id`) REFERENCES `professionals`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `waitlist_service_fk` FOREIGN KEY (`service_id`) REFERENCES `services`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `waitlist_unit_fk` FOREIGN KEY (`unit_id`) REFERENCES `business_units`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `waitlist_appointment_fk` FOREIGN KEY (`appointment_id`) REFERENCES `appointments`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `waitlist_opportunity_fk` FOREIGN KEY (`opportunity_id`) REFERENCES `appointment_waitlist_opportunities`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
