CREATE TABLE `professional_unavailabilities` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(36) NOT NULL,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `professional_id` BIGINT UNSIGNED NOT NULL,
  `unit_id` BIGINT UNSIGNED NULL,
  `type` ENUM('BLOCK', 'DAY_OFF', 'VACATION', 'SICK_LEAVE', 'PERSONAL', 'OTHER') NOT NULL,
  `title` VARCHAR(160) NOT NULL,
  `reason` VARCHAR(1000) NULL,
  `starts_at` DATETIME(3) NOT NULL,
  `ends_at` DATETIME(3) NOT NULL,
  `all_day` BOOLEAN NOT NULL DEFAULT FALSE,
  `repeats_weekly` BOOLEAN NOT NULL DEFAULT FALSE,
  `recurrence_ends_at` DATETIME(3) NULL,
  `active` BOOLEAN NOT NULL DEFAULT TRUE,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `professional_unavailabilities_public_id_key` (`public_id`),
  INDEX `pua_tenant_professional_period_active_idx` (`tenant_id`, `professional_id`, `starts_at`, `ends_at`, `active`),
  INDEX `pua_tenant_type_active_idx` (`tenant_id`, `type`, `active`),
  CONSTRAINT `professional_unavailabilities_tenant_id_fkey` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `professional_unavailabilities_professional_id_fkey` FOREIGN KEY (`professional_id`) REFERENCES `professionals`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `professional_unavailabilities_unit_id_fkey` FOREIGN KEY (`unit_id`) REFERENCES `business_units`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
