import { type PrismaClient } from '../../database-client/client.js';
import { IntegrationUnavailableError, type WhatsAppControlTest, type WhatsAppInstanceDiagnostics, type WhatsAppInteractiveButton, type WhatsAppOperationResult, type WhatsAppReplyButtonType, type WhatsAppSendOutcome } from './integration-delivery.js';
import { EVOLUTION_WHATSAPP_CAPABILITIES, type WhatsAppDeliveryProvider } from './whatsapp-provider.js';
import { type WhatsAppConnectionResult } from './whatsapp-connection.js';
import { EvolutionWhatsAppClient } from './evolution-whatsapp-client.js';
import { type CredentialsCipher } from '../payments/gateway/credentials-cipher.js';
import { normalizeWhatsAppPhone } from './whatsapp-phone.js';
export class EvolutionWhatsAppDelivery implements WhatsAppDeliveryProvider {
  public constructor(private readonly client: PrismaClient, private readonly evolution: EvolutionWhatsAppClient, private readonly cipher?: CredentialsCipher) {}
  public readonly provider = 'EVOLUTION' as const;
  public readonly capabilities = EVOLUTION_WHATSAPP_CAPABILITIES;
  private async config(tenantId: bigint) { const settings = await this.client.tenantWhatsAppSettings.findUnique({ where: { tenantId } }); if (settings?.selectedProvider && settings.selectedProvider !== 'EVOLUTION') throw new IntegrationUnavailableError('Evolution não é o provider selecionado.'); const row = await this.client.tenantWhatsAppConfig.findUnique({ where: { tenantId_provider: { tenantId, provider: 'EVOLUTION' } } }); if (!row || !row.active || row.connectionStatus !== 'CONNECTED') throw new IntegrationUnavailableError('Evolution não configurada ou conectada.'); if (!this.cipher) throw new IntegrationUnavailableError('Criptografia de credenciais não configurada.'); const token = this.cipher.decrypt(row.encryptedAccessToken).token; if (typeof token !== 'string' || token.trim() === '') throw new IntegrationUnavailableError('Token da instância Evolution ausente.'); return { row, token }; }
  public async send(tenantId: bigint, to: string, text: string) { const result = await this.sendPlainText(tenantId, to, text); if (result.status === 'FAILED') throw new Error(result.message); }
  public async sendPlainText(tenantId: bigint, to: string, message: string): Promise<WhatsAppSendOutcome> { try { const phone = normalizeWhatsAppPhone(to); if (phone === null) return { externalMessageId: null, status: 'FAILED', httpStatus: 400, errorCode: 'EVOLUTION_INVALID_PHONE', message: 'O telefone informado é inválido.' }; const { token } = await this.config(tenantId); const response = await this.evolution.sendText(token, phone, message); return { externalMessageId: response.messageId ?? response.id ?? null, status: 'SENT', httpStatus: 200, errorCode: null, message: 'Mensagem enviada pela Evolution GO.' }; } catch (error) { const details = error !== null && typeof error === 'object' ? error as { code?: unknown; statusCode?: unknown } : {}; const invalidToken = details.code === 'EVOLUTION_UNAUTHORIZED'; const code = invalidToken ? 'EVOLUTION_INVALID_TOKEN' : 'EVOLUTION_PROVIDER_ERROR'; return { externalMessageId: null, status: 'FAILED', httpStatus: typeof details.statusCode === 'number' ? details.statusCode : null, errorCode: code, message: invalidToken ? 'O token da instância Evolution não foi aceito.' : 'Não foi possível enviar pela Evolution GO.' }; } }
  public sendInteractiveButtons(_tenantId: bigint, _to: string, _message: string, _buttons: WhatsAppInteractiveButton[], _replyType?: WhatsAppReplyButtonType): Promise<WhatsAppSendOutcome> { return Promise.resolve({ externalMessageId: null, status: 'FAILED', httpStatus: 501, errorCode: 'EVOLUTION_INTERACTIVE_NOT_IMPLEMENTED', message: 'Interações Evolution serão implementadas em etapa posterior.' }); }
  public testConnection(tenantId: bigint, _input?: { instanceId?: string; token?: string }): Promise<WhatsAppConnectionResult> { return this.config(tenantId).then(() => ({ connected: true, code: 'WHATSAPP_CONNECTED' as const, message: 'Evolution configurada.', httpStatus: null, externalCode: null })).catch(() => ({ connected: false, code: 'WHATSAPP_CREDENTIALS_MISSING' as const, message: 'Evolution não configurada.', httpStatus: null, externalCode: null })); }
  public configureReceivedWebhook(_tenantId: bigint, _url: string): Promise<WhatsAppOperationResult> { return Promise.resolve({ ok: false, httpStatus: 501, externalCode: 'EVOLUTION_WEBHOOK_NOT_IMPLEMENTED', message: 'Webhook Evolution será implementado em etapa posterior.', externalMessageId: null, queuedId: null }); }
  public configureStatusWebhook(tenantId: bigint, url: string) { return this.configureReceivedWebhook(tenantId, url); }
  public inspectInstance(): Promise<WhatsAppInstanceDiagnostics> { const probe = { ok: false, httpStatus: 501, message: 'Diagnóstico Evolution será implementado em etapa posterior.', payload: null }; return Promise.resolve({ instance: probe, queue: probe }); }
  public runControlTest(tenantId: bigint, to: string, message: string): Promise<WhatsAppControlTest> { return this.sendPlainText(tenantId, to, message).then((text) => ({ phoneCheck: { ok: true, httpStatus: null, message: 'Destinatário validado no envio.', payload: null }, text: { ok: text.status !== 'FAILED', httpStatus: text.httpStatus, externalCode: text.errorCode, message: text.message, externalMessageId: text.externalMessageId, queuedId: null } })); }
}
