CREATE TABLE `subscription_plan_changes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(36) NOT NULL,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `subscription_id` BIGINT UNSIGNED NOT NULL,
  `current_plan_id` BIGINT UNSIGNED NOT NULL,
  `target_plan_id` BIGINT UNSIGNED NOT NULL,
  `current_billing_cycle` ENUM('MONTHLY','QUARTERLY','SEMIANNUAL','ANNUAL','CUSTOM') NOT NULL,
  `target_billing_cycle` ENUM('MONTHLY','QUARTERLY','SEMIANNUAL','ANNUAL','CUSTOM') NOT NULL,
  `current_period_starts_at` DATETIME(3) NOT NULL,
  `current_period_ends_at` DATETIME(3) NOT NULL,
  `source_paid_amount_cents` BIGINT UNSIGNED NOT NULL,
  `unused_credit_cents` BIGINT UNSIGNED NOT NULL,
  `target_price_cents` BIGINT UNSIGNED NOT NULL,
  `amount_due_cents` BIGINT UNSIGNED NOT NULL,
  `currency` CHAR(3) NOT NULL,
  `status` ENUM('PENDING_PAYMENT','SCHEDULED','PAID','APPLIED','CANCELED','EXPIRED','FAILED') NOT NULL DEFAULT 'PENDING_PAYMENT',
  `requested_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `payment_provider` VARCHAR(64) NULL,
  `payment_reference` VARCHAR(191) NULL,
  `stripe_checkout_session_id` VARCHAR(191) NULL,
  `stripe_payment_intent_id` VARCHAR(191) NULL,
  `stripe_subscription_id` VARCHAR(191) NULL,
  `expires_at` DATETIME(3) NOT NULL,
  `paid_at` DATETIME(3) NULL,
  `applied_at` DATETIME(3) NULL,
  `effective_at` DATETIME(3) NULL,
  `failure_reason` VARCHAR(500) NULL,
  `metadata` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  UNIQUE INDEX `subscription_plan_changes_public_id_key` (`public_id`),
  INDEX `subscription_plan_changes_tenant_id_status_idx` (`tenant_id`,`status`),
  INDEX `subscription_plan_changes_subscription_id_status_idx` (`subscription_id`,`status`),
  INDEX `subscription_plan_changes_expires_at_status_idx` (`expires_at`,`status`),
  CONSTRAINT `subscription_plan_changes_tenant_id_fkey` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `subscription_plan_changes_subscription_id_fkey` FOREIGN KEY (`subscription_id`) REFERENCES `tenant_subscriptions` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `subscription_plan_changes_current_plan_id_fkey` FOREIGN KEY (`current_plan_id`) REFERENCES `commercial_plans` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `subscription_plan_changes_target_plan_id_fkey` FOREIGN KEY (`target_plan_id`) REFERENCES `commercial_plans` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
